### DISCUSSION TITLE
Using okteto locally without an image registry

### DISCUSSION THREAD

**Discussion by jgonera** [okteto/okteto#3676] [Q&A] [answered]
Hi,

I'd like to use Okteto as a replacement for Docker Compose by using it with a local Kubernetes cluster that comes with Docker Desktop. I tried both using existing `docker-compose.yaml` (although `okteto` had problems parsing my volumes) and `okteto.yaml`. The problem I run into is that Okteto, as opposed to Docker Compose, always tries to fetch Docker images from an external registry:

```
Error checking image at registry okteto.global/my-service-server:okteto-with-volume-mounts-0a6e3ab345045041941ae9834fff6be6b82a990d648eed42e9a92dc2f8ff5dc7: error checking image at registry okteto.global/my-service-server:okteto-with-volume-mounts-0a6e3ab345045041941ae9834fff6be6b82a990d648eed42e9a92dc2f8ff5dc7: error getting image tag with digest: error getting image digest: error getting image descriptor: Get "https://okteto.global/v2/": tcp dial failed for okteto.global:443: dial tcp: lookup okteto.global on 192.168.1.1:53: no such host
```

Is there a way to tell Okteto to only use local image cache, and if the image doesn't exist there, then build it using `Dockerfile`?

My `okteto.yaml`:

```yaml
build:
  server:
    context: .
    target: base
dev:
  server:
    autocreate: true
    command: npm run dev
    environment:
      NODE_ENV: development
    forward:
      - 8080:8080
    sync:
      - .:/opt/app
      - ~/.aws:/root/.aws
    volumes:
      - /opt/app/node_modules
 ````

**Comment by jLopezbarb** [comment]
Hi @jgonera, which CLI version are you using? Can you try upgrading it and try again? We fixed an issue in the latest version

**Reply by jgonera** [reply]
Sorry for a slow reply. I get this now for the above config:

```
$ okteto up
 i  Using default @ docker-desktop as context
 x  'build.server.image' is required if your cluster doesn't have Okteto installed
$ okteto version
okteto version 2.16.4
```

Is there a way to make `okteto` build an image on demand?

**Reply by jLopezbarb** [reply]
Hi again @jgonera. You will need to specify where you want to build the image on the build section. So it will look like something like this:
```yaml
build:
  server:
    context: .
    target: base
    image: jgonera/server:latest
dev:
  server:
    autocreate: true
    command: npm run dev
    environment:
      NODE_ENV: development
    forward:
      - 8080:8080
    sync:
      - .:/opt/app
      - ~/.aws:/root/.aws
    volumes:
      - /opt/app/node_modules
```
