### ISSUE TITLE
Unknown syncthing error

### ISSUE THREAD

**Issue by kbc8894** [okteto/okteto#1053]
I'm newbie for k8s.
I have two k8s cluster.
one is working with okteto, but other is not working with okteto.
I don't know what is a problem, please give me hint or keyword.
please help me.

**Describe the bug**
not working 'okteto up'

**To Reproduce**

❯ okteto up
Installing dependencies...
syncthing-macos-amd64-v1.9.0.zip 9.78 MiB / 9.78 MiB  100.00% 58.81
 ✓  Dependencies successfully installed
Deployment hello-world doesn't exist in namespace default. Do you want to create a new one? [y/n]: y
Failed to connect to the synchronization service
    Check your development container logs for errors: 'kubectl logs hello-world-647ccb978-4mvq7'
    Run 'okteto down -v' to reset the synchronization service and try again.

❯ kubectl logs hello-world-647ccb978-4mvq7
USER:0
Copying configuration files to /var/syncthing ...
cp: cannot create regular file '/var/syncthing/cert.pem': Permission denied
cp: cannot create regular file '/var/syncthing/config.xml': Permission denied
cp: cannot create regular file '/var/syncthing/key.pem': Permission denied

❯ okteto down -v
 ✓  Development container deactivated
 i  Run 'okteto push' to deploy your code changes to the cluster
 ✓  Persistent volume removed

❯ okteto up
Deployment hello-world doesn't exist in namespace default. Do you want to create a new one? [y/n]: y
 ✓  Development container activated
 x  Unknown syncthing error
    Help us improve okteto by filing an issue in https://github.com/okteto/okteto/issues/new.
Please include the file generated by 'okteto doctor' if possible.
Then, try to run 'okteto down -v' + 'okteto up'  again

**Expected behavior**
working 'okteto up'

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Mojave

**Additional context**
Add any other context about the problem here (e.g okteto.yml, k8s manifests, logs)
- okteto-doctor file
  - https://bit.ly/2EFXmxV

**Comment by pchico83** [comment]
@kbc8894 is the same okteto manifest working on a cluster, but not in the other?
could you share your okteto manifest?

**Comment by kbc8894** [comment]
> @kbc8894 is the same okteto manifest working on a cluster, but not in the other?
> could you share your okteto manifest?
here is manifest.
it is working on cluster A, but not cluster B.
I use manifest of vscode-remote-go repo.
``` 
name: hello-world
image: okteto/golang:1
workdir: /okteto
command: ["bash"]
volumes:
  - /go/pkg/                # persist go dependencies
  - /root/.cache/go-build/  # persist go build cache
  - /root/.vscode-server    # persist vscode extensions
securityContext:
  capabilities:
    add:
    - SYS_PTRACE            # required by the go debugger
forward:
  - 8080:8080
persistentVolume:
  enabled: true
```
