### ISSUE TITLE
Okteto stacks environments accepting map syntax

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1070]
**Is your feature request related to a problem? Please describe.**
I want to define my variables with this format:
```
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'notifications'
```

**Describe the solution you'd like**
It works. Now, the only syntax accepted is:
```
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=notifications
```
