### ISSUE TITLE
unable to reverse forward

### ISSUE THREAD

**Issue by horacimacias** [okteto/okteto#1170]
**Describe the bug**
I'm trying to reverse forward traffic from development container localhost:8888 to my local machine 8888.
I already have a server running on my machine's localhost:8888 (which is what I want my development environment to connect to)

**To Reproduce**
1. Do `okteto up` with an okteto.yaml file containing something like:

```
reverse:
  - 8888:8888
```

output is:

```
couldn't forward traffic to your development container: local port 8888 is already in-use in your local machine
```
Maybe I'm miss-understanding the configuration; of course local port 8888 is already in-use which is what I want to connect to.
Is there any way to allow my development container to connect to my localhost's service?

**Expected behavior**
Expect `okteto up` to work and traffic to be forwarded

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: 10.15.2

**Comment by rberrelleza** [comment]
@horacimacias can you share your okteto.yaml configuration? (please remove anything confidential)

**Comment by horacimacias** [comment]
sure, thanks for checking this.
My okteto.yaml is far from special:

```yaml
name: myproject
image: okteto/rust:1.47.0
command: bash
sync:
- .:/usr/src/app
persistentVolume: {}
context: kubernetes-admin@kubernetes
reverse:
  - 8888:8888
```
