### ISSUE TITLE
How to use secrets in k8s

### ISSUE THREAD

**Issue by atcaoyufei** [okteto/okteto#1208]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: xx
        name: test
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_DSN
            value: $MONGO_DSN
```

### How does MONGO_DSN use secrets
