### ISSUE TITLE
Support label in port forwarding rules that include a service name

### ISSUE THREAD

**Issue by sameera466** [okteto/okteto#1274]
okteto supports port forwarding like this -
forward:
- 5012:5012
- 3306:some-service:3306

Here some-service is the name of a service in the same namespace, okteto should support usage of labels also instead of just service names

**Comment by pchico83** [comment]
Hi @sameera466, this would be a nice addition!
Do you have something in mind for the syntax to specify labels?
One option is to have the string based syntax, and a map based syntax for advanced cases:
```
forward:
  - localPort: 5012
     remotePort: 5012
  - localPort: 3306
     remotePort: 3306
     labels:
        app: mysql
```

**Comment by sameera466** [comment]
```
forward:
  - localPort: 5012
    remotePort: 5012
  - localPort: 3306
    remotePort: 3306
    name: mysql-service
    labels:
       app: mysql
```

Adding the name, just in case someone wants to use the service name
