### ISSUE TITLE
Modify the request/limit for all containers that are in the Sidecar

### ISSUE THREAD

**Issue by Juanfree** [okteto/okteto#1294]
**Is your feature request related to a problem? Please describe.**
On the cluster that I am working, we have limitranges configured and the min request is 256Mi.

When I try to make the okteto up I receive and error, because I have the issue as I said with the limitranges.

**Describe the solution you'd like**
We able to inject some configuration in order to increase/modify the request/limit.

**Comment by pchico83** [comment]
We could provide a section to fine tune the init container. Something like this:
```
initContainer:
   image: xxx
   resources:
      requests:
          cpu: xxx
          memory: xxx
      limits:
          cpu: xxx
          memory: xxx

```
