### ISSUE TITLE
Ability to replace existing volumeMount

### ISSUE THREAD

**Issue by lkrzyzanek** [okteto/okteto#1301]
**Is your feature request related to a problem? Please describe.**
It would be great to have ability to override the existing volumeMount when the `mountPath` is already taken by original container.

The use case is:
1. My deployment has init container that prepares data and store them into pod's volume.
2. The volume is mapped to main container (apache httpd) to serve the content. This is default deployment.
3. I want Okteto to overwrite those files by "sync" mechanism but I can't because the mountPath needs to be unique. I got:
```
 x  couldn't activate your development container (httpd): Deployment.apps "simple-content-dev" is invalid: spec.template.spec.containers[0].volumeMounts[5].mountPath: Invalid value: "/var/www/html/": must be unique
```

**Describe the solution you'd like**
If the volumeMount in original container exists it will be replaced by Okteto's volumeMount. Default could be "disabled" but optionally enabled within `extended sync notation` - https://okteto.com/docs/reference/manifest#sync-string-required 

e.g.
```yaml
sync:
  folders: 
    - theme:/var/www/html/theme/
    - home:/var/www/html/
  replaceExistingVolumeMount: true
```

**My `okteto.yaml`**
```yaml
name: simple-content-dev
command: httpd -D FOREGROUND
sync:
  - theme:/var/www/html/theme/
  - home:/var/www/html/
forward:
 - 8080:8080
```
