### ISSUE TITLE
Add support for configMaps in the manifest 

### ISSUE THREAD

**Issue by ammolitor** [okteto/okteto#1304]
I am using Okteto to support a development team, and some parts of the development environment are dynamic. We handle these configurations in k8s using configMaps. (for example start a shared service (like a database), and look at a known configMap for connection info). 

I'd like to be able to reference a configMap in a similar manner as with a pod definition. things like the `envFrom` and the `volumeMount` in the Pod example below. 
```
---
apiVersion: v1
kind: Pod
metadata:
  name: ammolitor-dev
spec:
  containers:
    - name: devel
      image: centos:7
      command: [ "/bin/bash" ]
      envFrom:
      - configMapRef:
          name: proxy-env-vars
      args: ["-c", "while true; do sleep 60; done"]
      volumeMounts:
        - name: db-cluster
          mountPath: /etc/dbconfig
          readOnly: true
  volumes:
    - name: db-cluster
      configMap:
        name: db-config
        items:
          - key: "cluster-file"
            path: "cluster-file"
```

At this point I am working around the `envFrom` example by hard coding the env variables in the okteto.yaml, and including the `/etc/dbconfig/db-cluster` file in the `sync:` directive. 

The main challenge with my workarounds is that if the [k8s] configuration changes I have to ask each developer on my team to make a local [okteto] config change to accompany it.
