### ISSUE TITLE
Allow the secret in the services 

### ISSUE THREAD

**Issue by danny-stytch** [okteto/okteto#1316]
**Is your feature request related to a problem? Please describe.** 
I have a service that runs as two stacks with the same codebase and different configurations, and there are times where I want to develop both at the same time. I found that the [services](https://okteto.com/docs/reference/manifest#services-object-optional) field in the okteto.yaml should cover this use case. However, my developer container listed under services cannot start since the service I'm running requires access to a private golang library (internal to my company). I tried adding the [secrets](https://okteto.com/docs/reference/manifest#secrets-string-optional) field under service, but the services documentation says that the secret field isn't supported.

**Describe the solution you'd like**
Ideally, I could write a Okteto.yaml file like the following:
```yaml
name: deployment
image: okteto/golang:1
command: bash
securityContext:
  capabilities:
    add:
    - SYS_PTRACE
volumes:
- /go/pkg/
- /root/.cache/go-build/
workdir: /usr/src/app
sync:
- .:/usr/src/app
- ../internal-go-common/:/usr/src/invite-go-common
forward:
- 2346:2346
- 8080:8080
secrets:
  - $HOME/.gitconfig:/root/.gitconfig:400
services:
  - name: deployment-2
    command: ["go", "run", "/usr/src/app/cmd/app/main.go"]
    image: okteto/golang:1
    workdir: /usr/src/api
    sync:
      - .:/usr/src/app
      - ../internal-go-common/:/usr/src/invite-go-common
    volumes:
    - /go/pkg/
    - /root/.cache/go-build/
    secrets:
    - $HOME/.gitconfig:/root/.gitconfig:400
```
**Describe alternatives you've considered**
Before trying services, I had two different okteto.yaml files for each environment, but I could only run one at a time.
