### ISSUE TITLE
Automatic SSL endpoints are not being generated

### ISSUE THREAD

**Issue by raschmitt** [okteto/okteto#1340]
**Describe the bug**

I'm trying to deploy a simple [.Net Api](https://github.com/raschmitt/net-core-docker-sample), with the manifests provided below,  and make use of Automatic SSL endpoints as described [here in the docs](https://okteto.com/docs/cloud/ssl).

So I added the auto-ingress annotation to my service manifest:

```yml
  dev.okteto.com/auto-ingress: "true"
```

Yet when I go to the UI I can't see any endpoints created.

![Screenshot from 2021-03-20 23-08-45](https://user-images.githubusercontent.com/11604696/111891394-9374af00-89d1-11eb-916f-b95f750f4122.png)

**To Reproduce**

1. Apply the provided manifests
2. Go to the UI and try to find the deployment endpoints

**Expected behavior**

I would like to see an endpoint for my deployment on the UI.

**Additional context**

- service.yml

```yml
kind: Service
apiVersion: v1
metadata:
  name: net-core-docker-sample-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: net-core-docker-sample
    restype: pod
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  ```
- deployment.yml

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-core-docker-sample-deployment
spec:
  replicas: 1
  progressDeadlineSeconds: 180
  selector:
    matchLabels:
      app: net-core-docker-sample
  template:
    metadata:
      labels:
        app: net-core-docker-sample
    spec:
      containers:
      - name: net-core-docker-sample
        image: raschmitt/net-core-docker-sample:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 3
          periodSeconds: 10
```
