### ISSUE TITLE
Extended notation for stacks.resources to define requests

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1392]
**Is your feature request related to a problem? Please describe.**
The current Okteto Stack `resources` field only allow to define the `limits` of the service:
https://okteto.com/docs/reference/stacks#resources-object-optional

An extended should be supported to define `requests`.

**Describe the solution you'd like**
These two notations should be allowed:

```
resources:
  cpu: 300m
  memory: 500Mi
```

and:

```
resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 700Mi
```
and storage resources should be defined in the `volumes` section https://github.com/okteto/okteto/issues/1391
