### ISSUE TITLE
Support "labels" and "annotations" for stack endpoints

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1407]
**Is your feature request related to a problem? Please describe.**
I want to set annotations on ingresses created by stack endpoints.

**Describe the solution you'd like**
Support for this syntax:

```
endpoints:
  movies:
    labels:
        .....
    annotations:
        .....
    rules:
    - path: /
      service: frontend
      port: 80
    - path: /api
      service: api
      port: 8080
```
