### ISSUE TITLE
Add option to use different environments with pipelines

### ISSUE THREAD

**Issue by davemaier** [okteto/okteto#1416]
**Is your feature request related to a problem? Please describe.**
I wan't to use okteto pipelines to deploy the same application in different environments (dev, stage, prod). Since the deployment steps and especially the secrets used might differ between the environments it would be useful to be able to define multiple different deployment methods in  `okteto-pipeline.yaml`.

**Describe the solution you'd like**
I would be great to have an additional option to define different deployment scripts (or environments) in `okteto-pipeline.yaml`. 
Maybe a structure like this would do the trick:
```
icon: https://plattform.ava.services/wp-content/themes/ava_theme/img/ava_logo.svg

environments:
  - name: 'dev'
    deploy:
      - okteto build -t ${OKTETO_REGISTRY_URL}:api api
      - okteto build -t ${OKTETO_REGISTRY_URL}:frontent frontend
      - okteto build -t ${OKTETO_REGISTRY_URL}:assist --build-arg SOME_SECRET=${SOME_SECRET_DEV}  assist
      - helm upgrade --install assist chart --set db=${MY_DB_URL_DEV}
  - name: 'stage'
    deploy:
      - okteto build -t okteto.dev/api:${OKTETO_GIT_COMMIT} api
      - okteto build -t okteto.dev/frontend:${OKTETO_GIT_COMMIT} frontend
      - okteto build -t okteto.dev/assist:${OKTETO_GIT_COMMIT} --build-arg SOME_SECRET=${SOME_SECRET_STAGE}  assist
      - helm upgrade --install assist chart --set tag=${OKTETO_GIT_COMMIT} db=${MY_DB_URL_STAGE}
 ```
Then the cli command for the pipeline could get another option like  `--environment` to pass in which script should be used.

**Describe alternatives you've considered**
If only the secrets should be different in the deployments, it would be sufficient if each namespace could have its own secrets (See https://github.com/okteto/cloud-feedback/issues/66). With the current toolset I could not find sufficient solution.

**Comment by pchico83** [comment]
We are considering supporting user-defined tasks in the okteto pipeline. For example, you might have:
```
    deploy:
      - okteto build -t ${OKTETO_REGISTRY_URL}:api api
      - okteto build -t ${OKTETO_REGISTRY_URL}:frontent frontend
      - okteto build -t ${OKTETO_REGISTRY_URL}:assist --build-arg SOME_SECRET=${SOME_SECRET_DEV}  assist
      - helm upgrade --install assist chart --set db=${MY_DB_URL_DEV}
    deploy-stage:
      - okteto build -t okteto.dev/api:${OKTETO_GIT_COMMIT} api
      - okteto build -t okteto.dev/frontend:${OKTETO_GIT_COMMIT} frontend
      - okteto build -t okteto.dev/assist:${OKTETO_GIT_COMMIT} --build-arg SOME_SECRET=${SOME_SECRET_STAGE}  assist
      - helm upgrade --install assist chart --set tag=${OKTETO_GIT_COMMIT} db=${MY_DB_URL_STAGE}
    test:
      - make tests
```
and you would have the option to run `okteto pipeline deploy`, `okteto pipeline deploy-stage` or `okteto pipeline test`. 
Would that cover your use case?
