### ISSUE TITLE
Add mount volumes to the Dockerfile in Okteto Stacks

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1439]
**Is your feature request related to a problem? Please describe.**
It is quite common to use data volumes in docker-compose to modify an official image. For example, to add a static file to nginx, you can do:

```
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html
```

This doesn't work in Okteto Stacks because volume mounts are ignored.

**Describe the solution you'd like**

When there is a mount volume as the sample above, automatically add the Dockerfile instruction `COPY ./public /usr/share/nginx/html` to the Dockerfile, or autogenerate a Dockerfile if it doesn't exist. This way, this docker-compose file will work in Okteto Stacks.
