### ISSUE TITLE
Support reduced notation for "endpoints"

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1450]
**Is your feature request related to a problem? Please describe.**
Apps usually only have an endpoint. The endpoint name seems redundant in this case, we could get it from the stack name.

**Describe the solution you'd like**
For this case:
```
name: movies
endpoints:
   movies:
       - path: /
          service: frontend
          port: 80
       - path: /api
          service: api
          port: 8080
```
supports this notation (which should be the notation documented in the first place): 
```
name: movies
endpoints:
     - path: /
        service: frontend
        port: 80
     - path: /api
        service: api
        port: 8080
```
and:
```
name: movies
endpoints:
   annotations:
      - kubernetes.io/ingress.class: "nginx"
   rules:
       - path: /
          service: frontend
          port: 80
       - path: /api
          service: api
          port: 8080
```
