### ISSUE TITLE
Option to configure syncthing verbosity

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1463]
**Is your feature request related to a problem? Please describe.**
Synthing creates a lot of logs, polluting my volumes.

**Describe the solution you'd like**
An option to configure the syncthing logs. For example, using the extended `sync` notation, it could look like this:
```
sync:
  folders:
    - .:/code
  logs: info
  rescanInterval: 50
```
