### ISSUE TITLE
Create several endpoints if the compose file have several ports

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1473]
**Is your feature request related to a problem? Please describe.**
My docker compose has a service with:
```
ports:
  - 8080:8080
  - 8081:8081
```
but only one port is exposed by Okteto Stacks. 

**Describe the solution you'd like**
In this case, create two endpoints automatically instead setting `public: true`:
```
endpoints:
    api-8080:
        path: /
        service: api
        port: 8080
    api-8081:
        path: /
        service: api
        port: 8081
```
