### ISSUE TITLE
Deduplicate volume entries

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1487]
**Describe the bug**
If I add my `workdir` folder as a `volume`, okteto up will fail with the following error:

```
➜ okteto up
 x  couldn't activate your development container
    Pod "my-app-7c967db774-8jwm9" is invalid: spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/app/": must be unique
```

I think we should deduplicate those entries to avoid errors. Also, we should catch that error and display something more user-friendly.

**Comment by pchico83** [comment]
@rberrelleza is this in a cluster managed by okteto= could you attach the doctor file?

**Comment by rberrelleza** [comment]
no, this happens if you have the same value in `workdir` and in `volumes`:

```
name: test
resources:
  requests:
    memory: "4Gi"
    cpu: "1"
  limits:
    memory: "32Gi"
    cpu: "4"
workdir: /app
command: ["bash"]
persistentVolume:
  enabled: true
  size: 32Gi
volumes:
  - /app/
sync:
  - .:/app/
autocreate: true
```
