### ISSUE TITLE
Support for env vars declared as a map and as a list

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1488]
**Describe the bug**
Docker-compose supports declaring env vars both as a map as well as a list (not sure why, or if one is deprecated).

This one works in okteto stacks:
```
version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: p0stgr3s_pass
    ports: 
      - '5432:5432'
    volumes:
      - calendso-db:/var/lib/postgresql/data

  calendso:
    build: .
    environment:
      DATABASE_URL: 'postgresql://postgres:p0stgr3s_pass@postgres:5432/postgres'
      GOOGLE_API_CREDENTIALS: "secret"
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '5555:5555'
volumes:
  calendso-db:
```

But this one doesn't:

```
version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_DB: postgres
      - POSTGRES_PASSWORD: p0stgr3s_pass
    ports: 
      - '5432:5432'
    volumes:
      - calendso-db:/var/lib/postgresql/data

  calendso:
    build: .
    environment:
     -  DATABASE_URL: 'postgresql://postgres:p0stgr3s_pass@postgres:5432/postgres'
     -  GOOGLE_API_CREDENTIALS: "secret"
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '5555:5555'
volumes:
  calendso-db:
```

Given that both are valid in docker-compose, I think we should support both.

**Comment by jLopezbarb** [comment]
The second syntax is not supported in docker-compose. 

Extracted from [here](https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment), the syntax accepted for environment are:


Map syntax:

```
environment:
  RACK_ENV: development
  SHOW: "true"
  USER_INPUT:
```
Array syntax:

```
environment:
  - RACK_ENV=development
  - SHOW=true
  - USER_INPUT
```

All these syntax are accepted. I've also tested the second syntax that you introduced (`-  DATABASE_URL: 'postgresql://postgres:p0stgr3s_pass@postgres:5432/postgres'`) on a docker-compose file and if you entered with the whitespace between key and value docker throws an error (`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.environment contains {"DATABASE_URL": "postgresql://postgres:p0stgr3s_pass@postgres:5432/postgres"}, which is an invalid type, it should be a string`), but if you set it like (`-  DATABASE_URL:'postgresql://postgres:p0stgr3s_pass@postgres:5432/postgres'`) it will be the same as the last example from the array syntax
