### ISSUE TITLE
Support for env vars without colon

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1489]
**Describe the bug**
Docker-Compose supports defining env vars as just the name, without value or colon sign. In this case, the value will come with an env var of the same day. In okteto, we require the colon always or we fail with a parsing error.

```
version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_DB: postgres
      - POSTGRES_PASSWORD
    ports: 
      - '5432:5432'
```
