### ISSUE TITLE
couldn't activate your development container - autocreate not working as expected

### ISSUE THREAD

**Issue by renepardon** [okteto/okteto#1553]
**Describe the bug**
I want to run multiple services with `okteto up`.
`autocreate: true` is set within okteto.yml manifest.

okteto up results in the following error:

>  x  couldn't activate your development container
    failed to get deployment default/api: deployments.apps "api" not found

**To Reproduce**
1. laravel new myservice (create a new laravel PHP project called 'myservice')
2. Copy this okteto.yml into the myservice/ directory:

```
name: myservice
autocreate: true
image: bitnami/laravel
command: bash
volumes:
  - /root/.composer/cache
sync:
  - .:/app
services:
  - name: api
    image: bitnami/laravel
    command: ["php", "artisan", "serve"]
    sync:
      - .:/app
  - name: worker
    image: bitnami/laravel
    command: ["php", "artisan", "queue:work", "redis"]
    sync:
      - .:/app
```

3. run `okteto up`

**Expected behavior**
I expect at least one tty being opened with a service named 'myservice'. There should also be two more services and deployments being created called 'api' and 'worker' which execute the expected commands in daemon mode.

**Desktop (please complete the following information):**
 - OS: Linux tuxedo 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Version: Ubuntu 20.04

**Additional context**
There is no "autocreate" allowed within the services so I thought the services will use the root `autocreate` option.
