### ISSUE TITLE
make the OKTETO_NAMESPACE automatically available for env vars and build args

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1571]
**Is your feature request related to a problem? Please describe.**

Could we make the OKTETO_NAMESPACE available for env vars and build args? A lot of applications require you to specify the URL when deploying them, so it would be  useful to be able to do something like this:

```
version: "3"
services:
  charts:
    ports:
    - 8080:8080
    build: 
      context: . 
      args: 
        URL: https://charts-$OKTETO_NAMESPACE.cloud.okteto.net
        TASK: dev
```

**Describe alternatives you've considered**
I can manual export the OKTETO_NAMESPACE env var, but it would be better if it's done automatically. I'd like for this to be available everywhere where we already extrapolate environment variables.
