### ISSUE TITLE
docker-compose build failing if the context is pointed to github repo

### ISSUE THREAD

**Issue by naveennamani** [okteto/okteto#1591]
**Describe the bug**
I'm using a docker-compose file, with build context as a github repo.

However the log showing it is failed to open the file.

```
x error building image for 'wekan': failed to create temporary build folder: open /https:/github.com/wekan/wekan.git/Dockerfile: no such file or directory
```

**To Reproduce**
1. Go to Okteto, click on Deploy
2. Select 'From compose' and use the following docker-compose
```
version: "3.8"

services:
  kanban:
      build:
        context: https://github.com/wekan/wekan.git

```
3. It will fail with the error no such file or directory.

**Expected behavior**
As docker-compose build context can have a github repo, it should
check for the github repo and clone it. And then search for the
Dockerfile.
