### ISSUE TITLE
Folder sync doesn't work with absolute paths (windows/powershell with Okteto CLI)

### ISSUE THREAD

**Issue by pnol** [okteto/okteto#1655]
**Describe the bug**
When I try to sync a folder from local using it's absolute path (C:/users/user/Documents/abc) an error is thrown : 
x  'persistentVolume.enabled' must be set to true to use subfolders in the 'sync' field

When I change the absolute path to a relative path (../../abc) the sync works as expected.
Also syncing the current directory (.) is working as expected.

Maybe the ':' in 'C:/...' is being recognized as a subfolder in this scenario?

**To Reproduce**
I use this okteto config file with an external fileshare:

```
name: pnom-pnoltest-ssa-20201-4
image: python
command: bash
autocreate: true
persistentVolume:
  enabled: false
externalVolumes:
- pnom-pnoltest-20201-pers-pvc:data:/data
sync:
- .:/usr/src/app # OK
- ../../testdata:/data # OK
# - C:/Users/pnolet/Desktop/testdata:/data #Failed
resources:
  requests:
    cpu: "1400m"
    memory: "5000Mi"
  limits:
    cpu: "1400m"
    memory: "5000Mi"
namespace: default
```

**Expected behavior**
I expect that just like using relative paths, absolute path would also work for syncing local folders

**Desktop (please complete the following information):**

- OS: Windows
- Terminal: powershell
- Okteto Version: 1.12.15

**Additional context**
