### ISSUE TITLE
Horizontal Pod Autoscaler failed to get cpu utilization: no metrics returned matched known pods

### ISSUE THREAD

**Issue by claudiuri** [okteto/okteto#1662]
**Describe the bug**
When testing if hpa I noticed that the pods don't increase because I can't catch the metrics

**To Reproduce**

1. `kubectl appy -f .`
2. `kubectl describe hpa`

**Expected behavior**
Hope the pods scale horizontally

**Desktop:**

- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]

**Additional context**
Manifest
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heavy-deploy
  labels:
    app: heavy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heavy-api
  template:
    metadata:
      labels:
        app: heavy-api
    spec:
      containers:
      - name: api-pod
        image: claudiuri/heavy-api
        resources:
          requests:
            cpu: 200m
            memory: 256M
          limits:
            cpu: 300m
            memory: 512M
        env:
        - name: PORT
          value: '8086'
        ports:
        - containerPort: 8086
          name: api-port
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      dev.okteto.com/generate-host: "true"
  name: heavy-api
  labels:
    app: heavy-api
spec:
  type: LoadBalencer
  selector:
    app: heavy-api
  ports:
  - protocol: TCP
    port: 8086
    name: svc-port
    targetPort: api-port
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: heavy-hpa
  labels:
    app: heavy-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heavy-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
```

`kubectl describe hpa`

 Warning  FailedComputeMetricsReplicas  25m (x12 over 28m)    horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed metrics for Deployment/claudiuri/heavy-deploy: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: no metrics returned matched known pods
  Warning  FailedGetResourceMetric       3m24s (x95 over 28m)  horizontal-pod-autoscaler  no metrics returned matched known pods
