### ISSUE TITLE
Remote SSH port refuses connection

### ISSUE THREAD

**Issue by Youngestdev** [okteto/okteto#1681]
**Describe the bug**
The remote port *2222* refuses connection in PyCharm. Here's an example of an Okteto manifest that won't trigger a SSH instance:

```yml
name: fastapi
command: bash
volumes:
- /root/.cache/pip
sync:
- .:/app
remote: 2222
reverse:
- 9000:9000
forward:
- 8080:8080
```

**To Reproduce**

Include this in your Okteto manifest:

```yml
remote: 2222
```

**Expected behavior**

After running `okteto up`, the SSH tunnel isn't started and connection to it are refused.
<img width="372" alt="Screenshot 2021-08-02 at 21 15 08" src="https://user-images.githubusercontent.com/31009679/127919513-bbf5affb-7b8b-4e9d-ac69-4c2ca5805224.png">
