### ISSUE TITLE
go: syncing: delete file: encountered directory when trying to remove file/symlink

### ISSUE THREAD

**Issue by iamnoah** [okteto/okteto#1709]
**Describe the bug**

I get this error and my shell terminates abruptly while running a go application:

```
 x  go: syncing: delete file: encountered directory when trying to remove file/symlink
```

**To Reproduce**

My okteto.yml is pretty basic:

```yaml
name: myapp 
labels:
  app: myapp
image: okteto/golang:1
context: minikube
command: /bin/bash
sync:
- ./:/okteto
- $HOME/.ssh/:/root/.ssh/
volumes:
  - /go
workdir: /okteto
forward:
- 7777:7777
```

After `okteto up`, just doing a basic `go run main.go`. Typically runs for a few minutes before exiting. 

**Expected behavior**

Shell doesn't exit and I can keep working.

**Desktop (please complete the following information):**

- OS: macOS
- Version 1.13.4

My .stignore should cover pretty much everything except the source code:

```
.git
*.exe
*.exe~
*.dll
*.so
*.dylib

# vendor folders
vendor

# Test binary, built with go test -c
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# dlv binary
__debug_bin

.idea
.github

main
```

I can't share the app source but it's just a simple REST app. No writing files or anything unless one of my dependencoies is doing it.

EDIT: While I was writing this up, it terminated just sitting at the bash prompt, so it's not something my application is doing.

**Comment by pchico83** [comment]
@iamnoah it could be because you are synching `$HOME/.ssh/:/root/.ssh/`. For ssh keys, it is better to use dev secrets:
https://okteto.com/docs/reference/manifest/#secrets-string-optional

**Comment by iamnoah** [comment]
@pchico83 that seems to be working, thanks!

```yaml
sync:
- ./:/okteto
secrets:
- $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:400
```
