### ISSUE TITLE
Be able to define syncthing foldertype per folder on manifest file

### ISSUE THREAD

**Issue by cristianodarocha** [okteto/okteto#1728]
**Is your feature request related to a problem? Please describe.**
Currently, all synced folders have been syncing using the "sendreceive" [syncthing folder type](https://docs.syncthing.net/users/foldertypes.html). Within our project, multiple users have been using okteto to have a remote development container closer to the production (and sensitive) data on Azure. Furthermore, those remote development containers enable better data analysis capabilities since engineers/developers can have more resources than within their laptops to crunch and analyze huge amounts of data. 

Most of those users have been using the file syncing capability to sync their source code but also to bring their own data to cloud as a way to enrich their analysis. However, a lot of security-related concerns have been raised since users can use the _sendreceive_ sync behavior to bring production/sensitive data from the cloud to their laptops and then it exposes severe vulnerabilities in terms of data leakage. In this context, a lot of users are getting frustrated with the fact that okteto might be considered as a NO-GO due to this vulnerability. In addition, a lot of users get frustrated with huge files (gigabytes) being synced back from cloud to laptop when they use the same synced folder to output their data analysis results.

**Describe the solution you'd like**
The proposed solution consists on extending the [sync annotation](https://okteto.com/docs/reference/manifest/#sync-string-required) to include the foldertype setting per folder since multiple folders can be mapped for syncing. In this context, the proposal consists on extending the folders' entry from <**local_folder>:<remote_folder>** to **<local_folder>:<remote_folder>:<folder_type>**. An example is presented as follows:
```
sync:
  folders:
    - ./src:/code:sendreceive
    - ./data:/data:sendonly
  verbose: false
  compression: true
  rescanInterval: 100
```

Therefore, the _foldertype_ setting is going to be used as an input for generating the syncthing config.xml file instead of having the _foldertype="sendreceive"_ as a static/hardcoded value.

In case no value is provided for the _foldertype_ setting, then _sendreceive_ should be the default value (keep it as the current situation).

**Describe alternatives you've considered**
An alternative consists on adding the foldertype setting to the sync annotation but it would apply the same policy for all folders which might be not ideal since it is good to have flexibility to define the policy (sendreceive, sendonly, receiveonly) per folder.

```
sync:
  folders:
    - ./src:/code
    - ./data:/data
  verbose: false
  compression: true
  rescanInterval: 100
  foldertype: receiveonly
```
