### ISSUE TITLE
Support for docker compose extensions ("x-nnnn" fields)

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1755]
**Is your feature request related to a problem? Please describe.**
My compose file has an extension like this:
```
x-env: &env
  environment:
    - SOME_ENV_VAR=123
  command: bash -c 'echo $$SOME_ENV_VAR'

services:
  first:
    <<: *env
    image: bash
  second:
    <<: *env
    image: bash  
```

and it fails with:
```
➜ okteto stack deploy
 x  Invalid stack manifest:
    - line 1: field x-env not found in type model.StackRaw
```

**Describe the solution you'd like**
It works, although the `x-nnnn` fields will be ignored, as indicated in the [Compose Spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#extension).
