### ISSUE TITLE
Node Module not found

### ISSUE THREAD

**Issue by markgarrigan** [okteto/okteto#1801]
npm start runs my app fine locally.
The container runs fine in kubernetes.
okteto up runs the app just fine

```
name: dss-uptime
namespace: workbench
command: ["npm", "run", "debug"]
securityContext:
  runAsUser: 2000
sync:
  - .:/usr/app
forward:
  - 9229:9229
  - 3000:3000
persistentVolume:
  enabled: true
  storageClass: managed-nfs-storage
```

Install a new npm package. Require the package in my code.

npm start runs my app fine locally.
The container runs fine in kubernetes.

okteto up no longer runs the app.

Error: Cannot find module 'needle'

I tried a number of random npm packages with the same result.

If I comment out the require line. okteto up works again.

I've done okteto down -v. I've rebuilt the container. I've deleted the deployment. Reinstalled the deployment. okteto up still won't work with a new package.
