### ISSUE TITLE
Bug when using command single string syntax with Stacks

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1821]
**Describe the bug**
Something is wrong when using the command single string syntax.

**To Reproduce**

This should work:
```
services:
  test:
     image: mysql
     command: ls & tail -f /dev/null
```
probably related to using double quotes vs single quotes
