### ISSUE TITLE
Bug: Directory name with _ is translated to - while deploying

### ISSUE THREAD

**Issue by Horizon733** [okteto/okteto#1863]
**Describe the bug**
While deploying my service on Okteto via github, my directory named as `custom_channels` is been trying to fetch as `custom-channels` 
Error will look like following image
<img src="https://user-images.githubusercontent.com/57827233/138244051-2e2dea44-9271-4084-8800-330175a9ff40.png" width="720">

**To Reproduce**

1. Create a directory with `_` in root directory of your okteto project
2. Deploy it on okteto
3. You will be able to see error on deployment logs as above screenshot shows

**Expected behavior**
While deploying it should have directly copied data from custom_channels and pasted in app/custom_channels instead of translating with `_` by `-`

**Additional context**
I am adding Dockerfile and docker-compose.yml data below
- Dockerfile

```dockerfile
FROM python:3.7.7-stretch AS BASE

RUN apt-get update \
    && apt-get --assume-yes --no-install-recommends install \
        build-essential \
        curl \
        git \
        jq \
        libgomp1 \
        vim

WORKDIR /app

# upgrade pip version
RUN pip install --no-cache-dir --upgrade pip

RUN pip install rasa==2.8.1

ADD config.yml config.yml
ADD domain.yml domain.yml
ADD credentials.yml credentials.yml
ADD endpoints.yml endpoints.yml
```
- docker-compose.yml
```yml
version: '3.4'
services:
  duckling:
    image: rasa/duckling:latest
    networks:
      - all

  rasa:
    image: portfolio-bot:latest
    build: "./"
    restart: always
    working_dir: /app
    volumes:
    - ./models:/app/models
    - ./data:/app/data
    - ./actions:/app/actions
    - ./custom_channels:/app/custom_channels
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\""
    ports:
    - '5006:5005'
    public: true
    networks:
    - all

  rasa-actions:
    build: "./"
    image: portfolio-bot:latest
    restart: always
    working_dir: /app
    volumes:
      - ./actions:/app/actions
      - ./custom_channels:/app/custom_channels
    command: ["rasa","run","actions"]
    ports:
    - '5055:5055'
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"

```
