### ISSUE TITLE
`depends_on` fails across stack manifests

### ISSUE THREAD

**Issue by conkiztador** [okteto/okteto#1891]
**Describe the bug**
In a stack defined with multiple docker-compose manifests, `depends_on` fails if a service in one manifest depends on a service in a different manifest.

This seems to be because `depends_on` is validated during unmarshalling: https://github.com/okteto/okteto/blob/1474c7a166e9415db76d7a9486477530e6a6ccaa/pkg/model/stack_serializer.go#L273

**To Reproduce**
```
db.yml:
  services:
    db:
      image: mariadb

app.yml:
  services:
    app:
      image: nginx
      depends_on:
      - db
```

```
$ okteto stack deploy -f db.yml -f app.yml
 x   Service 'app' depends on service 'db' which is undefined.
```
 
**Expected behavior**
`depends_on` should work across files.
