### ISSUE TITLE
Support the "dev.okteto.com/private: true" annotation for stack services

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1895]
I want to be able to mark one or more services in my stack as private, without having to define an endpoint object, or create any kubernetes resources. 

Something like this would be ideal, since it makes my manifest compliant with compose, but I can still take advantage of an okteto feature:

```
name: hello-world
services:
  hello-world:
    image: okteto.dev/hello-world
    labels:
      dev.okteto.com/private: "true"
    build: .
    ports:
    - 8080:8080
```

Today, this is possible by using the 'dev.okteto.com/auto-ingress: true' label, but I think that is a leaky abstraction, since ingress is a kubernetes thing.
