### ISSUE TITLE
okteto push doesn't restart the pod

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1992]
**Describe the bug**
I'm running `okteto push` after changing code. The command is building a new image and pushing it to my registry,  but it's not restarting the corresponding kubernetes deployment.

My okteto.yaml looks like this:

```
name: frontend
namespace: okteto
selector:
  app.kubernetes.io/part-of: okteto
  app.kubernetes.io/component: frontend
image: okteto/node:12
workdir: /app
command: ["bash"]
```

**Expected behavior**
I'd expect my deployment to be restarted since there's a new container available. 

**Desktop (please complete the following information):**
- Version 1.14.6
