### ISSUE TITLE
Support long syntax volume spec in Okteto Stacks.

### ISSUE THREAD

**Issue by jpf-okteto** [okteto/okteto#1995]
**Is your feature request related to a problem? Please describe.**
Docker compose v3 long syntax volume spec is not supported in Okteto Stacks.

**Describe the solution you'd like**
Being able to define a volume inside a service using long syntax.
https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3

**Describe alternatives you've considered**
Support both syntaxes at the custom `UnmarshallYAML` func for `StackVolume`. Only some types can be safely supported (e.g. `volume`).
https://github.com/okteto/okteto/blob/3a944e4fdba23505d717ab70309ae091b2a89381/pkg/model/stack_serializer.go#L1067-L1083

**Additional context**
Example `docker-compose.yml`:
```yaml
version: "3"

volumes:
  mydata:

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: mydata
        target: /data
```
