### ISSUE TITLE
Support for hooks based on synchronization events

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2025]
**Is your feature request related to a problem? Please describe.**
My app doesn't support hot reloading. I need to restart my app every time synchronization finishes.

**Describe the solution you'd like**
Support for defining hooks for synchronization events. For example, a hook when all files are synchronized.
We can use the `sync` extended notation:

```
sync:
  folders:
      - .:/
   hook: make restart app
```
