### ISSUE TITLE
Okteto behaviour of cloning the deployment (instead of modifying it) problematic with FluxCD

### ISSUE THREAD

**Issue by rkujawa** [okteto/okteto#2029]
**Describe the bug**
Somewhere between version 1.12 and current, Okteto has changed how the development container is started. Now the original deployment is cloned with `-okteto` suffix. This causes severe trouble with GitOps approach (at least as used by FluxCD v1) - both the original deployment and development deployment serve incoming requests after `okteto up`.

**To Reproduce**

1. Run Kubernetes cluster with FluxCD v1
2. Deploy an application with FluxCD in a developer's namespace
3. Use `okteto up` with file like:
```
---
name: refrigerator-api-deployment
autocreate: false
namespace: rkujawa
container: refrigerator-api
metadata:
  annotations:
    fluxcd.io/ignore: "true"
workdir: /app
command: /usr/bin/flask run -h 0.0.0.0
environment:
  FLASK_ENV: development
remote: 2222
forward:
  - 5000:5000
sync:
  - src:/app
persistentVolume:
  enabled: false
```
4. Deployment that is watched by FluxCD gets cloned. The cloned (`-okteto`) deployment has `fluxcd.ignore` annotation set, as specified in `okteto.yml`. The original deployment does not.
5. Okteto scales down the original deployment.
6. FluxCD sees that original deployment state is different than within Git, and scales up the deployment again.
7. I end up with a service for this application that has two deployments as backends (original and one cloned by Okteto), so any requests that come into the service, gets distributed in a round-robin fashion between the original and development container.

**Expected behavior**
`okteto up` starts a development container that *replaces* the original container. Current behaviour breaks this with FluxCD.

**Desktop (please complete the following information):**

- OS: Linux 
- Version: 1.14.8

**Additional context**
This makes Okteto unusable with Flux, I had to revert previously used version 1.12.15.

Is it possible to revert to the old behaviour of modifying existing deployment instead of cloning it (by means of a setting in `okteto.yml` or whatever other option)?

If not, is it possible to modify the original deployment, while doing `okteto up`, so that it gets `fluxcd.ignore` set automatically?
