### ISSUE TITLE
Okteto build from manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2038]
**Is your feature request related to a problem? Please describe.**
I want to define the images that I want to build in my okteto manifest.

**Describe the solution you'd like**

The new **okteto manifest** defines a section for building the images of your application:

```
# okteto.yml

build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
  api:
    context: api
    dockerfile: Dockerfile
```

Fields defining a build at the manifest:

- `image`: optional - tag for the image when pushing it to registry. This is optional when you are using okteto platform registry.
- `context`: required - where the Dockerfile for building the image is located
- `dockerfile`: optional - the name for the Dockerfile to use for building the image
- `target: optional - the stage at the dockerfile to use
- `args`: optional - the arguments passed when making the build

The command `okteto build` will now build all the images described in the manifest.

```bash
okteto build
```

```bash
okteto build frontend
```

Also, the current build command with tag flag can be run to achieve the previous behavior.

```bash
okteto build -t your.registry.com/frontend:dev
```
