### ISSUE TITLE
Support for defining git dependencies in the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2041]
**Is your feature request related to a problem? Please describe.**
The new okteto manifest enables the definition of git dependencies to deploy your application. When running okteto deploy, these dependencies are built and deployed as well as the services defined in the build section.

**Additional context**
In the first iteration, this feature will be only available if running in a cluster with the okteto server component (Okteto Cloud or Okteto Enterprise)

### Sample

```
dependencies:
  - https://github.com/okteto/movies-frontend
build:
  API: .
deploy:
  - helm upgrade --install movies chart --set image=${build.api.image} 
dev:
  api:
    command: ["bash"]
    sync:
      - .:/src
    forward:
      - 8080:8080
      - 9229:9229
```
