### ISSUE TITLE
stacks should allow empty environment variables

### ISSUE THREAD

**Issue by johnktims** [okteto/okteto#2050]
**Describe the bug**
Sometimes it's necessary to have an environment variable set without a value. `okteto stack deploy` removes environment variables without values.

**To Reproduce**

1. Create a `docker-compose.yml`
```
services:
  bash:
    image: bash:latest
    command: bash -c "env | grep _VAR"
    env_file:
      - .env1
```

2. Create `.env1`
```
➜ cat .env1
SOME_VAR=1
EMPTY_VAR=
```

3. Verify docker-compose allows empty variables
```
➜ docker-compose run --rm bash
EMPTY_VAR=
SOME_VAR=1
```

4. Show that okteto removes the empty variable
```
➜ okteto stack deploy
➜ k logs bash-597cc85c9c-f5tcz
SOME_VAR=1
```

**Expected behavior**
`EMPTY_VAR` is set even though it doesn't have a value.

**Desktop (please complete the following information):**

- OS: macOS
