### ISSUE TITLE
Support commands with a name in the okteto pipeline

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2085]
**Is your feature request related to a problem? Please describe.**
I have a pipeline with long commands, or multi line commands.
`okteto deploy` outputs looks weird both, in the CLI and the Okteto UI.

**Describe the solution you'd like**
CircleCI also have this problen. They support two syntaxs:

```
deploy:
  - okteto build -t okteto.dev/api:${OKTETO_GIT_COMMIT} api
  - okteto build -t okteto.dev/frontend:${OKTETO_GIT_COMMIT} frontend
  - helm upgrade --install movies chart --set tag=${OKTETO_GIT_COMMIT}
```

and

```
deploy:
  - name: Build api
    command: okteto build -t okteto.dev/api:${OKTETO_GIT_COMMIT} api
  - name: Build frontend
    command: okteto build -t okteto.dev/frontend:${OKTETO_GIT_COMMIT} frontend
  - name: Deploy
    command: helm upgrade --install movies chart --set tag=${OKTETO_GIT_COMMIT}ç
```

and, if defined, `name` is used in the tty/json output iinstead of the command.
