### ISSUE TITLE
Docker compose integration with `okteto deploy`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2095]
Support an extended syntax for docker-compose integration with the new okteto manifest.

The `deploy` field can be a list of commands, but also:

```
deploy:
  run:
     - kubectl apply -f k8s.yml
  compose: ./docker-compose.yml
```

or:

```
deploy:
  run:
     - kubectl apply -f k8s.yml
  compose:
    manifest: ./docker-compose.yml
    endpoints:
      - path: /
        service: frontend
        port: 80
      - path: /api
        service: api
        port: 8080
```

in both cases, `okteto build xxx` will work if `xxx` is denied in the compose file. Also, `okteto deploy` will build the images in the docker-compose if needed, and `okteto deploy --build` will build all the images in the compose file.
