### ISSUE TITLE
`okteto stack deploy` building image on every deploy

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2096]
**Describe the bug**
If I have a docker-compose like this one:

```
services:
  vote:
    build: vote
    ports:
      - 8080:8080
    volumes:
      - vote:/src

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data
```

The `vote` image is built on every `okteto stack deploy` because there is a mount volume, but it should only be built the first time.
