### ISSUE TITLE
Okteto manifest v2

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2157]
**Is your feature request related to a problem? Please describe.**
The current okteto manifest doesn't provide a way to deploy the application. Ideally, we should have a command that, if the app is not deployed, deploys the app first and then, activates the dev mode on a given service.

Also, especially for mono repos, there is usually a lot of redundancy about okteto manifests

**Describe the solution you'd like**

We are moving to a new manifest that let's you define the images you need to build, the commands to deploy your application, and the different dev containers of your application. Having a single manifest makes it easier to use [yaml anchors](http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html) to reuse definitions across dev containers.

# Goal

Unified development experience. Build, deploy and develop as part of the full experience.

## Okteto Manifest

The manifest revolves around the definition of a **development environment**. It is the mechanism to describe an entire application for remote development with Okteto, across multiple repositories.

The new `okteto.yml` will define all the necessary configurations to provide a unified experience based on the **Build → Deploy → Dev** phases, merging together our current `okteto-pipeline.yml` and `okteto.yml` manifests, while keeping retro-compatibility with them.

```yaml
build:       # List of images and how to build them.
deploy:      # List of commands to deploy the application. 
dev:         # Configuration of the development containers. 
```

### build (optional)

Contains the list of images to build for the services of the application.

```yaml
build:
  frontend:
    image: okteto/frontend
    context: frontend
    dockerfile: Dockerfile
    target:
    args:
      args1: value1
      args2: value2
  backend:
    image: okteto/backend
    context: backend
```

It is possible to refer to these images using this notation: ${build.service.image}, ${build.service.registry}, ${build.service.repository} and ${build.service.tag} in the rest of the manifesrt.

### deploy (optional)

Contains a sequential list of commands to deploy the application inside the development environment.

The goal of this command is to automate the deployment of the entire application for development but **separating the boundaries** of our tool and the way developers deploy their applications. It is usually a combination of stack/compose, helm, kubectl, and other okteto commands.

```yaml
name:
 deploy:
  - helm upgrade --install movies chart --set tag=${OKTETO_GIT_COMMIT}
  - kubectl apply -f manifest.yml
  ...
```

## dev (optional)

A map of development containers. The syntax is the same as the current okteto manifest, but they are indexed by name:

```yaml
dev:
  api:
    image: okteto/godev:1
    command: bash
    sync:
       - .:/usr/src/app
  webhook:
    image: okteto/godev:1
    command: bash
    sync:
       - .:/usr/src/app
```

## Single Manifest

This sample represents our **okteto/app** repo using a single manifest.

```yaml
build:
  api:
    context: api
  frontend:
    context: frontend
deploy:
  - helm upgrade --install movies chart --set api.image=${build.api.image} --set frontend.image=${build.frontend.image}
dev:
  frontend:
    command: yarn start
    sync:
      - .:/src
  api:
    command: ["bash"]
    sync:
      - .:/src
    forward:
      - 8080:8080
      - 9229:9229
```

## CLI

All CLI commands will now work in both okteto clusters and the open-source, providing a more unified experience between the open-source and the Okteto Platform. Also, one of the goals is to have a single command for each operation (build, deploy, dev) that has a clear mapping to a section in the okteto.yml file.

```bash
$ okteto [options] <command> <subcommand> [parameters]
```

### build

Build all the images (or a specific service image) as described in the `build` section of the `okteto.yml` file.

```
$ okteto build [image]
```

[Parameters](https://www.notion.so/ff79deeeeed1443d8a5d63f16c7749be)

- `image`
    - The image(s) to build by name. If not specified all images are built.

### deploy

Deploy the application to a namespace as described in the `deploy` section of the `okteto.yml` file. It creates a new namespace if needed based on the field `namespace` of the okteto manifest.

If necessary it will also build all related images if they weren’t previously built.

```
$ okteto deploy [--build]
```

### dev

The mother of all commands.

`okteto dev up` (alias `okteto up)` enables the development mode on a specific service of the application, as described in the `dev` section of the `okteto.yml` file.

`okteto dev up` comes to replace the current `okteto up` command, and in addition, it will trigger the **build** and **deploy** phases as part of a unified way of bringing developers from a code repository to a remote development experience.

If necessary it will also:

- **Deploy** the entire application if it was never deployed before.
- **Build** all related images if they weren’t previously built.

If `[service]` is not specified and there is only one `dev` in the okteto.yml file, that service is chosen. If there are more than one service in the okteto.yml file, the CLI prompts for available services to pick one.

```
$ okteto dev [service] [--build] [--deploy]  [<command>]
```

### destroy

Destroys the application of a development environment (all the resources created by `okteto deploy` or `okteto up`.

```
$ okteto destroy
```
