### ISSUE TITLE
Integrate Okteto Stacks into the Okteto Manifest v2

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2162]
**Is your feature request related to a problem? Please describe.**

Implement a `compose` section as part of the `deploy` section of the [manifest v2](https://github.com/okteto/okteto/issues/2157). 

Example of a built-in compose support:

```yaml
name: app
deploy:
  compose: ./docker-compose.yml
```

Example of a built-in compose support with extended features:

```yaml
name: app
deploy:
  compose:
    manifest: ./docker-compose.yml
    endpoints:
      - path: /
        service: frontend
        port: 80
      - path: /api
        service: api
        port: 8080
```

**Describe the solution you'd like**

The okteto manifest v2 should infer sensible defaults if there is just a docker-compose in the repo.
Examples of this are:

- `okteto build frontend` should work if `frontend` is a service in the docker-compose file
- `okteto deploy` should build the docker images in the compose file if they don't exist
- `okteto deploy --build` should always build the docker images in the compose file
- `okteto up frontend` should work if `frontend` defines host volumes in the docker-compose file
