### ISSUE TITLE
stack: database ports are not getting an endpoint and should throw a warning

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2176]
**Describe the bug**
I have a database defined in the stack and I don't know why I don't get an endpoint. 

**To Reproduce**
Run this stack
```
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
```

**Expected behavior**
If one of the ports is listed in the ports that are never public https://okteto.com/docs/reference/stacks/#ports-int-optional show a warning to the user saying that the ports is not exposed and recommend him to use okteto up to get access to it
