### ISSUE TITLE
Support `attachTo` as an alternative to `services` in the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2211]
[services](https://www.okteto.com/docs/reference/manifest/#services-object-optional) provides a way to put on dev mode several containers at the same time. For example:

```
name: web
command: ["sh", "-c", "./run_web.sh"]
sync:
  - .:/app
services:
  - name: worker
    command: ["sh", "-c", "./run_celery.sh"]
    sync:
      - .:/app
```

the syntax in the new okteto manifest will look like this:
```
dev:
    web: 
        command: ["sh", "-c", "./run_web.sh"]
        sync:
            - .:/app
        services:
           - name: worker
             command: ["sh", "-c", "./run_celery.sh"]
             sync:
                - .:/app
```
which isn't very clear. 

A more flattened and clearer syntax would be:

```
dev:
    web: 
        command: ["sh", "-c", "./run_web.sh"]
        sync:
            - .:/app
    worker:
        attachTo: web
        command: ["sh", "-c", "./run_celery.sh"]
        sync:
            - .:/app
```
where `attachTo` means `worker` dev mode is activated when you run `okteto up web` (same behavior than `services` today).

*attachTo*. should be also supported in docker-compose via a label/annotation.
