### ISSUE TITLE
Support for having a volume shared by two services 

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2213]
**Is your feature request related to a problem? Please describe.**
I want to be able to share data between two services defined in my docker-compose.

```
version: "3"
services:
  a:
    volumes:
      - contract-data:/nau/contracts/
  b:
    volumes:
      - contract-data:/nau/contracts/
volumes:
  contract-data:
```

**Additional context**
When we translate, we could put the two services on the same pod as a way to support this. It's a common enough pattern, and I think this would make things easier for developers, without requiring more complex storage drivers.

**Comment by RongxinZhang** [comment]
This is mostly for `docker-compose.yml` files.
There could be a note in the docs: https://www.okteto.com/docs/reference/manifest/#volumes-string-optional which helps people know about this before it's implemented.

**Comment by rberrelleza** [comment]
@RongxinZhang good point!  

if we decide not to support this feature, then we should have a clear error message and update the docs.

**Comment by jLopezbarb** [comment]
We haven't discussed about this yet. I'll reopen for now

**Comment by jmacelroy** [comment]
I was just getting a setup to test this out and it appears that it is working now. I updated a fork of github.com/okteto/compose-getting-started to look like...

```
➜  compose-getting-started git:(shared-volume) ✗ cat docker-compose.yml
services:
  vote:
    build: vote
    scale: 2
    ports:
      - 8080:8080
    volumes:
      - redis:/data

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:
```

This will create the services, `redis-0`, `vote-0` and `vote-1`. If I exec into one of the pods and write to a file in one of the containers I can then read that data on the other two.
