### ISSUE TITLE
okteto stack deploy should fail if 'endpoints' has a reference to a non-existing service

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2225]
**Describe the bug**
If I have a docker-compose file like this:

```
endpoints:
  - service: this-is-not-here
    path: /
    port: 8080
  - service: api
    path: /api
    port: 3000
services:
  web:
    build: frontend
    image: okteto.dev/frontend
    ports:
    - 8080
  api:
    build: api
    image: okteto.dev/api
    ports:
    - 3000
```

`okteto stack deploy` should fail during the manifest parsing phase since the `endpoints` section has a reference to the non-existing service `this-is-not-here`.

Today, we ignore this error and deploy the application. This makes this kind of errors very hard to catch.

**Desktop (please complete the following information):**

- OS: macOS
- Version 1.15.2
