### ISSUE TITLE
okteto build target ignored 

### ISSUE THREAD

**Issue by remche** [okteto/okteto#2229]
**Describe the bug**
okteto wont use the specified target to build image.

**To Reproduce**
`docker build -f docker/Dockerfile  --target dev .` → build dev stage
`okteto build -f docker/Dockerfile  --target dev .` → build prod stage
`okteto up --build` → build prod stage

**Desktop (please complete the following information):**

- OS: Linux w/ Docker 20.10.12

**Additional context**

_okteto.yml extract_
```yaml
image:
  name: k3d-registry.localhost:12345/chronosheep:test-build
  dockerfile: ./docker/Dockerfile
  target: dev
sync:
  - ./django-application:/app
```
_Dockerfile_
```Dockerfile
FROM nginx/unit:1.26.0-python3.9 AS base

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE chronosheep.settings

COPY ./docker/requirements.txt /app/
COPY ./docker/requirements.txt /app/

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

COPY ./data /data
COPY ./django-application /app
RUN python /app/manage.py collectstatic
COPY ./docker/config.json /docker-entrypoint.d/

FROM base AS dev
RUN apt update && apt install -y netcat
RUN pip install --no-cache-dir -r requirements.dev.txt


FROM base
EXPOSE 8000
```
