### ISSUE TITLE
Empty variables are not expanded with its value from the environment

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2239]
**Describe the bug**
Variable expansion doesn't work with this syntax:

```
services:
  nginx:
    image: nginx
    environment:
      TEST_ENV:
```

but they do with this one:
```
services:
  nginx:
    image: nginx
    environment:
      TEST_ENV: ${TEST_ENV}
```
