### ISSUE TITLE
Autoinject image envvars on compose deploy

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2256]
**Describe the bug**
Kubernetes autoinjects envvars. For example, this compose doesn't work:

```
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_BROKER_ID: "1"

  zookeeper:
    image: zookeeper:3.7
    ports:
      - 2181
```

doesn't work because kubernetes injects a `KAFKA_PRT` envvar that is already defined in the image. 

We can avoid this issue if we autoinject the variables in the docker image when deploying wurstmeister/kafka:2.12-2.5.0
