### ISSUE TITLE
`okteto test` to run my e2e tests

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2272]
**Is your feature request related to a problem? Please describe.**
I want to run my e2e tests in my remote development environment.

**Describe the solution you'd like**
Define a `test` section in the okteto manifest to run e2e tests.

```
test:
  image: ${build.backend-test.image}
  variables:
    DEBUG_MODE: true
  workdir: /src
  command: make tests
```

Launching this command runs the **test container** and streams its logs in standard output until the test container finishes successfully or fails. `okteto test` triggers the **build** and **deploy** phases as part of a unified way of bringing developers from a code repository to test.

If necessary it will also:

- **Deploy** the entire application if it was never or unsuccessfully deployed.
- **Build** all related images if they weren’t previously built.

```
$ okteto test [--build] [--deploy] [--namespace] 
```
