### ISSUE TITLE
okteto up doesn't show complete error message when one of the deploy commands fails

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/okteto#2288]
**Describe the bug**
When running `okteto up` or `okteto up --deploy` and one of the commands in the `deploy` section fails the error message shown gets trimmed off if there is less space on the terminal instead of being moved to the next line. This makes it hard to debug.
 
**To Reproduce**

1. Clone https://github.com/okteto/chat
2. Replace the okteto.yaml with:

```
icon: https://github.com/okteto/chat/raw/master/icon.png
build:
  chat:
    dockerfile: Dockerfile.dev
deploy:
  - kubectl apply -f dev/postgres.yml
  - kubectl apply -f dev/redis.yml
  - helm upgrade chat chart --install --set image.tag=${OKTETO_GIT_COMMIT}
dev:
  chat:
    environment:
      - RAILS_ENV=development
    command: ["bash"]
    sync:
      - .:/app
    forward:
      - 1234:1234
      - 5234:db:5234
```
3. Run `okteto up`
4. If your terminal is not wide enough for the complete error message to be show then the message gets trimmed:

![image](https://user-images.githubusercontent.com/56963264/155533456-7bedc411-b93a-45d2-b49d-4e49be9b82b5.png)

**Expected behavior**
If the terminal size is small then the error message should be broken down into new lines instead of being trimmed off.

**Desktop (please complete the following information):**

- OS:  macOS
- Okteto CLI Version: 2.0.0-rc.2

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)
