### ISSUE TITLE
Support for Pseudo TTY and interactive mode.

### ISSUE THREAD

**Issue by hmmhmmhm** [okteto/okteto#2354]
![스크린샷 2022-03-15 오후 1 01 34](https://user-images.githubusercontent.com/38493722/158303858-fac64620-d330-4b0d-a3fe-97f7d1888754.png)

![스크린샷 2022-03-15 오후 12 52 40](https://user-images.githubusercontent.com/38493722/158303817-817f2c8c-5974-402d-96d7-d5776cb639ea.png)

![스크린샷 2022-03-15 오후 1 04 45](https://user-images.githubusercontent.com/38493722/158304166-78a42669-4dfe-4c5e-8ff8-baa2c6659420.png)

Currently, tty emulation is not supported in okteto,
which prevents server programs from operating that require continued use of tty pipes.

**Comment by pchico83** [comment]
@hmmhmmhm in order to use `tty` you should configure an okteto manifest and run `okteto up`. 
Resources created by `okteto stack deploy` are in detached mode and cannot run `tty` emulation.

**Comment by hmmhmmhm** [comment]
Q. Is it possible to operate if I write it in okteto manifest as below?
I'm not sure how to put the tty option into the okteto manifest,
so I'd appreciate it if you could check it.

```
name: some-okteto
persistentVolume:
  enabled: false
services:
  web:
    build: .
    stdin_open: true
    tty: true
```
