### ISSUE TITLE
`okteto down` integration with compose it's broken

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2367]
**Describe the bug**
If I have a docker-compose like this one:
```
services:
  result: 
    build:
      context: result
    ports:
      - 4000:4000
    command: nodemon server.js
    depends_on:
      - postgresql
    volumes:
      - result:/app

  vote:
    build:
      context: vote
    command: mvnw spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    volumes:
      - vote:/app

  worker:
    build:
      context: worker
    depends_on:
      - postgresql
    volumes:
      - worker:/app

  postgresql:
    image: docker.io/bitnami/postgresql:14
    environment:
      - POSTGRES_PASSWORD=okteto
      - POSTGRES_USER=okteto
      - POSTGRES_DB=votes
    ports:
      - 5432
```

I can run `okteto up vote`, but `okteto down vote` gives me an error:
```
 i  Using pchico83 @ demo.okteto.dev as context
 x  Okteto manifest has no 'dev' section. Configure it with 'okteto init'
```

I think the same happens with `okteto exec vote`.
I also have this `okteto.yml` file:

```
deploy:
  commands:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm upgrade --install kafka bitnami/kafka -f kafka/values.yml --version 14.5.0
  compose: docker-compose.yml
```
