### ISSUE TITLE
Using local registry with nss-myhostname

### ISSUE THREAD

**Issue by remche** [okteto/okteto#2416]
**Describe the bug**
Using a local registry with [nss-myhostname](https://man7.org/linux/man-pages/man8/nss-myhostname.8.html) name (i.e. registry.localhost) does not work with okteto 2.

**To Reproduce**
Use `k3d-registry.localhost:12345/image` as image name for build.service.image.
Use `okteto up` will thrown an error, trying to resolve `k3d-registry.localhost` (see logs).
Note that `okteto build` works fine.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version okteto 2.0.1

**Additional context**

Workaround is to use
`localhost:12345/image`  for build.service.image.
and
`k3d-registry.localhost:12345/image`  for dev.service.image.

```
Error checking image at registry k3d-registry.localhost:12345/xxx: error getting image tag digest: Get "https://k3d-registry.localhost:12345/v2/": dial tcp: lookup k3d-registry.localhost on xx.xx.xx.xx:53: no such host; Get "http://k3d-registry.localhost:12345/v2/": dial tcp: lookup k3d-registry.localhost on xx.xx.xx.xx:53: no such host
```

**Comment by pchico83** [comment]
@remche thanks for reporting this, looks like a very interesting use case.
Could you rephrase the workaround, seems like you said to use two different values at `build.service.image`.

Als, could you share your okteto manifest?

**Comment by remche** [comment]
> @remche thanks for reporting this, looks like a very interesting use case. Could you rephrase the workaround, seems like you said to use two different values at `build.service.image`.

oops, sorry, I just fixed that in issue description.
* for build image we need to use `localhost` as registry because of the `Error checking image...` bug ;
* for dev image we use `k3d-registry.localhost` because we use [K3d managed registry](https://k3d.io/v5.2.0/usage/registries/#using-k3d-managed-registries).

Using K3d + Okteto is a great combo for on premise dev environment !

> Als, could you share your okteto manifest?

v2 manifest :
```
build:
  chronosheep:
    image: k3d-registry.localhost:12345/chronosheep
    dockerfile: ./docker/Dockerfile
    target: dev
deploy:
  compose:
    - ./okteto-stack.yml
dev:
  chronosheep:
    autocreate: true
    image: k3d-registry.localhost:12345/chronosheep
    command: |
      /usr/local/bin/docker-entrypoint.sh unitd --no-daemon --control unix:/var/run/control.unit.sock
    sync:
      - ./django-application:/app
    forward:
      - 8000:80
      - 5432:db:5432
      - 9000:minio:9000
      - 9001:minio:9001
```

FYI, this is the v1 manifest which did not have the issue : 

```name: chronosheep
image:
  name: k3d-registry.localhost:12345/chronosheep:dev
  dockerfile: ./docker/Dockerfile
  target: dev
command: |
  /usr/local/bin/docker-entrypoint.sh unitd --no-daemon --control unix:/var/run/control.unit.sock
sync:
  - ./django-application:/app
interface: 0.0.0.0
forward:
  - 8000:80
  - 5432:db:5432
  - 9000:minio:9000
  - 9001:minio:9001
autocreate: true
```
