### ISSUE TITLE
Support to deploy a subset of docker compose services in the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2500]
**Is your feature request related to a problem? Please describe.**
My okteto manifest looks like this:
```
deploy:
   compose: docker-compose.yml
...
``` 
but I need to deploy only a subset of services
 
**Describe the solution you'd like**
Something like this:
```
deploy:
   compose:
      file: docker-compose.yml
      services:
        - a
        - b
...

**Comment by AgustinRamiroDiaz** [comment]
Should we still have to be backwards compatible for this notation?
```yaml
deploy:
   compose: docker-compose.yml

**Comment by AgustinRamiroDiaz** [comment]
Question 2: What should happen for multiple docker-compose files? I don't think it's a real use case but it would look something like this
```yaml
deploy
    compose:
        - file: docker-compose
          services:
            - a
            - b
        - file: another-docker-compose
          services:
            - c

**Comment by pchico83** [comment]
@AgustinRamiroDiaz yes to both. we have to support all different options, and document them

**Comment by AgustinRamiroDiaz** [comment]
@pchico83 @jLopezbarb To be sure, we will support then 4 different schemas:

1: Only one compose file
```yaml
deploy:
   compose: docker-compose.yml
```

2: Multiple compose files with their "to-be deployed" services
```yaml
deploy
    compose:
        - file: docker-compose
          services:
            - a
            - b
        - file: another-docker-compose
          services:
            - c
```

3: One compose file with its "to-be deployed" services
```yaml
deploy:
   compose:
      file: docker-compose.yml
      services:
        - a
        - b
```

4: Multiple compose files
```yaml
deploy
    compose:
        - docker-compose
        - another-docker-compose
```
