### ISSUE TITLE
Support name param for dependencies 

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2501]
**Is your feature request related to a problem? Please describe.**
When adding dependencies to my okteto manifest, i want to specify the name of the dependency. now the name is inferred from the repo https://github.com/okteto/okteto/blob/master/pkg/model/serializer.go#L716

**Describe the solution you'd like**
support `name` as field inside the dependency model

**Comment by teresaromero** [comment]
After investigating this, the problem was not the name at the dependencies section, but the name assigned to an okteto compose manifest, when this is part of a deploy command inside an okteto manifest.

So, for dependencies at the okteto manifest, this can be defined short or extended:

Short:
```
name: catalog

dependencies:
  - https://github.com/okteto/movies-frontend-with-divert
  - https://github.com/okteto/movies-rentals
```

Extended:
```
name: catalog

dependencies:
    frontend:
        repository: https://github.com/okteto/movies-frontend-with-divert
    rentals:
        repository: https://github.com/okteto/movies-rentals
```

When using extended, the name for the dependency (dev environment for that dependency) should be taken from the name assigned at the manifest, in this case frontend and rentals. Also, a manifest can have a name informed, so the dev environment for that manifest should be name, in this case, catalog.

When a manifest has a deployment of a compose file, like so:
```
name: catalog

dependencies:
    frontend:
        repository: https://github.com/okteto/movies-frontend-with-divert
    rentals:
        repository: https://github.com/okteto/movies-rentals

deploy:
    - okteto deploy -f mongodb-compose.yml
```

When transforming the compose into manifest v2,  the name for the manifest was inferred from repo, or from the name flag, so, even though `name` is defined for okteto.yaml, `name` for the first command of deploy of this manifest, was not being transmitted to the compose. This also affected the dependencies which had a compose deployment, so 2 dev environments where created when deploying this manifests: 1 called `catalog` and other called `movies-catalog` which is the name of the repository.

Fixing this will require updating the cli version at the installer component, as the pipelines from dependencies are done by it. Also, there is an issue at the installer, which needs to be solved prior to include this fix into it.
https://github.com/okteto/app/issues/3632
