### ISSUE TITLE
okteto up can't run same command as deploy

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2511]
**Describe the bug**
If I run a script on `okteto up` command, It gives me an error saying `command not found` but when I run on `okteto deploy` everything runs successfully

**To Reproduce**
Use https://github.com/okteto/microservices-demo-compose and modify the docker-compose vote result as 
  ```
vote:
    build:
      context: vote
    command: mvnw spring-boot:run
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - postgresql
      - kafka
    volumes:
      - vote:/app
```

**Expected behavior**
It should work successfully, if the deploy command can run the command `okteto up` should work also

**Desktop (please complete the following information):**

- MacOS
- okteto version 2.1.0
