### ISSUE TITLE
`okteto up` fails when a `docker-compose.yaml` file is present

### ISSUE THREAD

**Issue by jarojasm95** [okteto/okteto#2575]
**Describe the bug**
Running `okteto up` with a `docker-compose.yaml` file in the same directory fails with `Error checking image at registry`

**To Reproduce**

1. Define a simple docker-compose.yaml
```yaml
x-common-args: &common-args
  HASH: "${HASH:-local}"

version: '3.8'
services:
  installer:
    image: "installer:${HASH:-local}"
    build:
      context: .
      dockerfile: build/installer.Dockerfile
  base:
    image: "base:${HASH:-local}"
    depends_on: [installer]
    build:
      context: build
      dockerfile: base.Dockerfile
  server:
    image: "server:${HASH:-local}"
    depends_on: [installer, base]
    build:
      context: components
      dockerfile: ../build/server.Dockerfile
      args:
        <<: *common-args
```
3. Define an `okteto.yaml` in the same directory
```yaml
name: server
imagePullPolicy: IfNotPresent
container: server
command: [bash]
sync:
  - .:/root
```
3. Try `okteto up`
> Error checking image at registry base:local: error getting image tag digest: GET https://index.docker.io/v2/library/base/manifests/local: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/base Type:repository]]

**Expected behavior**
The `docker-compose.yaml` would be ignored, the `okteto up` command works just fine if the `docker-compose.yaml` file is deleted

**Desktop (please complete the following information):**

- OS: macOS
- Version: 2.1.0

**Additional context**
The `docker-compose.yaml` is simply being used as a "build definition" file, so that all the docker images can be easily built using a single command: `docker-compose build`. There are no other "compose" features being used in this file. Additionally, the `base` image is used as a stage in building the `server` image.

**Comment by AdrianPedriza** [comment]
@jarojasm95 was due to the fact that you were using your local registry when pushing the built images. To fix this problem you should change your images name value on your docker-compose file to **okteto.dev/{image-name}:{image-tag}**

in your case, it would be:
````

x-common-args: &common-args
  HASH: "${HASH:-local}"

version: '3.8'
services:
  installer:
    image: "okteto.dev/installer:${HASH:-local}"
    build:
      context: .
      dockerfile: build/installer.Dockerfile
  base:
    image: "okteto.dev/base:${HASH:-local}"
    depends_on: [installer]
    build:
      context: build
      dockerfile: base.Dockerfile
  server:
    image: "okteto.dev/server:${HASH:-local}"
    depends_on: [installer, base]
    build:
      context: components
      dockerfile: ../build/server.Dockerfile
      args:
        <<: *common-args
````
