### ISSUE TITLE
okteto.yml with autocreate set to true fails on okteto 2.x

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2585]
**Describe the bug**
Doing okteto up on a manifest like this:
```
name: XXX 
image: LINK_TO_MY_DOCKER_IMAGE
imagePullPolicy: Always
namespace: YYY
workdir: /tmp
autocreate: true
initContainer:
  image: okteto/bin:1.3.4
command:
  - bash
forward:
  - 8080:8080
serviceAccount: mlp-spark 
```

Fails with this error:
```
Application 'XXX' not found in namespace 'YYY '
    Verify that your application is running and your okteto context is pointing to the right namespace
    Or set the 'autocreate' field in your okteto manifest if you want to create a standalone development container
    More information is available here: https://okteto.com/docs/reference/cli/#up
```

**To Reproduce**
The user reported that this worked fine on a previous version of Okteto CLI

okteto version: 2.1.0
vs code extension: v0.4.1
VS code version: 1.66.2

**Comment by rberrelleza** [comment]
user mentioned that moving to the v2 format worked fine. 
```
dev:
  XXXX:
    autocreate: true
    namespace: YYYY
    initContainer:
     image: okteto/bin:1.3.4
    image: LINK_TO_MY_DOCKER_IMAGE
    command: bash
    workdir: /tmp
    sync:
      - .:/usr/src/app
    forward:
      - 8080:8080
    serviceAccount: mlp-spark
```


This might be an issue with how the extension manages the v1 vs v2
