### ISSUE TITLE
'okteto up' doesn't interpret '$PWD' in the volume section of a docker-compose

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2597]
**Describe the bug**
I'm trying to deploy https://github.com/rberrelleza/play-with-docker/blob/master/docker-compose.yml. The volumes section looks like this:

```
    pwd:
        # pwd daemon container always needs to be named this way
        container_name: pwd
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/; if [ -e /runbin/pwd ]; then /runbin/pwd  -save /pwd/sessions -name l2; else go run api.go -save /pwd/sessions -name l2; fi'
        volumes:
            # since this app creates networks and launches containers, we need to talk to docker daemon
            - /var/run/docker.sock:/var/run/docker.sock
            # mount the box mounted shared folder to the container
            - $PWD:/go/src
            - sessions:/pwd
```

When deployed, $PWD is converted to a string, instead of evaluating it to the current folder
