### ISSUE TITLE
okteto up fails with volumespec error after changing the image

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2599]
This was reported in Slack. This error happened after the user changed the image to alpine, and ran okteto up again.

```
Couldn't activate your development container
    error updating kubernetes volume claim: PersistentVolumeClaim "web-okteto" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
        ... // 2 identical fields
        Resources:        {Requests: {s"storage": {i: {...}, Format: "BinarySI"}}},
        VolumeName:       "pvc-8ac52988-c057-49de-b1c6-c2a444b816cd",
-       StorageClassName: &"standard",
+       StorageClassName: &"okteto-standard",
        VolumeMode:       &"Filesystem",
        DataSource:       nil,
  }

```

**Comment by rberrelleza** [comment]
Reference https://kubernetes.slack.com/archives/CM1QMQGS0/p1650954140112709?thread_ts=1650951477.382719&channel=CM1QMQGS0&message_ts=1650954140.112709

**Comment by jmacelroy** [comment]
@rberrelleza would the correct behavior in this case be to catch the error, instruct the user to run okteto down -v followed by okteto up? That's what I think should be done as the disk can't change class without recreating it and it seems like there may be data loss repercussions if okteto were to destroy the disk for them.

**Comment by rberrelleza** [comment]
Yes, I think that's a good approach.

Although, in this specific case, the user didn't set the storageClass at all (they are using okteto cloud), so there might be something else lurking there.

**Comment by teresaromero** [comment]
After digging on this i could reproduce the error using cloud.
The user is adding a storageClass field at the dev manifest (from conversatiuon https://kubernetes.slack.com/archives/CM1QMQGS0/p1650954140112709?thread_ts=1650951477.382719&channel=CM1QMQGS0&message_ts=1650954140.112709) 

```
name: test
namespace: test-losunny

build:
  web:
    context: WebsiteNew
    dockerfile: WebsiteNew/Dockerfile

deploy:
  compose: docker-compose.yml

dev:
  web:
    image: registry.cloud.okteto.net/test-losunny/test-web
    command: sh
    workdir: /app
    sync:
      - .:/app
    forward:
      - 30007:30007
    persistentVolume:
      enabled: true
      storageClass: standard
      size: 0.5Gi
```

So when `okteto up` is run using cloud for the first time, a PVC for `web` is created, but this is created using the `okteto-standard` storageClass as at cloud we don't support other than `okteto-standard` or `csi-okteto-standard` and the first one is forced to be use if the pvc is set with other value for this field.

For this case, the user runs okteto up for the first time, and dev container is up and running. When the user changes the image to alpine, is not this event that causes the error, but the event that now PVC setting is still having `standard` as storageClass and now is an update of this resource, instead of a creation, so, as the original PVC has been created as `okteto-standard` this is not a compatible change.

There is a piece of code that is checking PVC values, but is comparing pvc object against dev marshalled object, not taking into account what the existent k8s PVC has as values. Should we return an error when the storageClass is being changed from the original PVC? I guess this would be related to https://github.com/okteto/okteto/issues/2600

For this issue, i propose the solution would be to the user to not use `storageClass: standard` when using Cloud, and either use `storageClass: okteto-standard` or none so the default will be applied. 

cc: @rberrelleza @jmacelroy
