### ISSUE TITLE
Error message is not helpful when the context defined in build doesn't exist

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2626]
**To Reproduce**
I defined an okteto.yml like this:

```
name: app

build:
  api:
    context: api
  frontend:
    context: frontend
deploy:
  - helm upgrade --install movies chart --set api.image=${OKTETO_BUILD_API_IMAGE} --set frontend.image=${OKTETO_BUILD_FRONTEND_IMAGE}
dev:
  api:
    command: ["bash"]
    forward:
      - 8080:8080
      - 9229:9229
    sync:
      - api:/usr/src/app
  frontend:
    command: npm start
    sync:
      - frontend:/usr/src/app
```

My repo doesn't have an `api` or `frontend` folder. 

When deploying, I get the following error:

```
Found okteto manifest on /okteto/src/okteto.ymlUnmarshalling manifest...Unmarshalling compose...x Invalid manifest:
- line 18: field dependencies not found in type model.deployInfoRaw
- line 20: field dev not found in type model.deployInfoRaw
See https://okteto.com/docs/reference/manifest/ for details
exit status 1
```

**Expected behavior**
I'd expect a clear error like: "folder API doesn't exist" or something like that.
