### ISSUE TITLE
`endpoints` not working in my okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2659]
**Describe the bug**
I had this okteto manifest:

```
deploy:
  endpoints:
    kafka-reader:
      - path: /api
        service: kafka-reader
        port: 3000
    kafka-ui:
      - path: /
        service: kafka-ui
        port: 8090

  compose: ./okteto-compose.yml
```

And `ednpoints` were not created. I had to move my `endpoints` to the `okteto-compose.yml` to make it work

**Comment by jmacelroy** [comment]
If the compose file doesn't have any endpoints this will work. If the compose file *has* endpoints this will work. There is only a failure when there a merge is required.

**Comment by teresaromero** [comment]
@pchico83 after a while trying to reproduce this issue i can't seem to make it work with the information described.

i'm working with movies-with-compose repo, creating an okteto.yaml like so:

```
deploy:
  endpoints:
    movies:
      - port: 80
        service: movies
        path: /
      - port: 8080
        service: api
        path: /api
  compose: ./docker-compose.yml
```

and the compose does not have any endpoints declared. In this case the endpoints are deployed correctly, the only issue i get is when i do not add the endpoints under `endpoints.movies` in which case i get the error that can't create the ingress without a name, because name for the ingress in empty (i guess this is the issue reported by @jLopezbarb) 

can you add more details on how to reproduce this bug (repository used, and exact steps to reproduce?) also, what is the expected behavour, as i see there are couple different expectations depending on where and how the endpoints spec is declared.

- services have public ports `80:80` -> endpoints are deployed when compose is deployed
- services have private ports `80` and okteto manifest have endpoints section -> endpoints are deployed 
- services have private ports `80` and compose have endpoints section -> endpoints are deployed (in this case when no name is assigned to the endpoints set, the repo name is inferred)
- both compose and okteto manifest have the endpoints section, i get a warning that the ones at the manifest will be used, they get deployed

cc: @jLopezbarb
