### ISSUE TITLE
`okteto context` opens bad auth page

### ISSUE THREAD

**Issue by mladedav** [okteto/okteto#2665]
**Describe the bug**
When I run `okteto context` and choose an okteto cloud context it redirects me to `https://auth/authorization-code?redirect=http...` instead of `https:://cloud.okteto.com/auth/authorization-code?...`.

When I manually fix the URL I get logged in.

**To Reproduce**
Have an okteto cloud context and set a default to it.

**Expected behavior**
Redirect to the correct URL.

**Desktop (please complete the following information):**

- OS: Windows
- Version 10
- Okteto 2.1.0 & 2.3.0-rc

**Comment by mladedav** [comment]
I have just noticed I have a context called `https://cloud.okteto.com` which logs in correctly and everything works and a context named `okteto` which is taken from my kubeconfig (for kubectl access to the okteto cloud namespace). When trying to use the kube config okteto it still wants to authenticate through the okteto cloud but it fails.

**Comment by teresaromero** [comment]
@mladedav hi! could you share your kubeconfig file so we can see how the contexts are configured? thnks

**Comment by mladedav** [comment]
I had to delete a lot of contexts (for obvious reasons). This was the only one okteto-related I noticed.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://...:443
  name: cloud_okteto_com
contexts:
- context:
    cluster: cloud_okteto_com
    namespace: mladedav
    user: c36e79c0-ce29-48aa-8f48-87c4d4be3beb
  name: okteto
kind: Config
preferences: {}
users:
- name: c36e79c0-ce29-48aa-8f48-87c4d4be3beb
  user:
    token: ...
```
