### ISSUE TITLE
Global registry optimization should only work if `image` isn't defined

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2666]
**Describe the bug**
I have this compose file:
```
services:
  frontend:
    image: okteto.dev/frontend:dev
    build: .

  api:
    image: okteto.dev/api:dev
    build: .
```

And my images aren't built each time I redeploy my repo.
This is because the global registry optimization is detecting okteto.dev/frontend:dev already exists.

**Expected behavior**
The global registry optimization should only work with autogenerated image names
