### ISSUE TITLE
`okteto up` does not generate deploy section

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2669]
**Describe the bug**
User found: When running `okteto up` in the microservices-demo repo and prompted with creating the manifest, the command fails due to a weird behavior in the deploy
![image](https://user-images.githubusercontent.com/49416765/167697989-e91e4e97-d81e-4978-9609-5e750561eadd.png)
![image](https://user-images.githubusercontent.com/49416765/167698248-40891bc9-d192-48ee-98fb-6f39e91690fc.png)

**To Reproduce**

1. Clone the microservices-demo repo
2. Run `okteto up`
3. Type `y` to configure the manifest

**Expected behavior**
`okteto up` should work

**Additional context**
The okteto.yml generated:
```
name: microservices-demo

# The build section defines how to build the images of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#build
build:

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_GRAPHS_REGISTRY: image registry
  #  - OKTETO_BUILD_GRAPHS_REPOSITORY: image repo
  #  - OKTETO_BUILD_GRAPHS_IMAGE: image name
  #  - OKTETO_BUILD_GRAPHS_TAG: image tag
  graphs:
    context: graphs
    dockerfile: graphs/Dockerfile

# The deploy section defines how to deploy your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#deploy
# deploy:
#   commands:
#   - name: Deploy
#     command: echo 'Replace this line with the proper 'helm' or 'kubectl' commands to deploy your development environment'


# The dependencies section defines other git repositories to be deployed as part of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#dependencies
# dependencies:
#   - https://github.com/okteto/sample


# The dev section defines how to activate a development container
# More info: https://www.okteto.com/docs/reference/manifest/#dev
dev:
  microservices-demo:
    image: okteto/python:3
    command: bash
    sync:
      - .:/usr/src/app
    forward:
      - 8080:8080
    reverse:
      - 9000:9000
    autocreate: true
    volumes:
      - /root/.cache/pip
```
