### ISSUE TITLE
okteto up --deploy --build fails due to missing Dockerfile

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2671]
**Describe the bug**
I have this manifest:

```
name: microservices-demo
build:
  result:
    context: result
    dockerfile: result/Dockerfile

  vote:
    context: vote
    dockerfile: vote/Dockerfile

  worker:
    context: worker
    dockerfile: worker/Dockerfile

  worker-dev:
    context: worker
    dockerfile: worker/Dockerfile
    target: dev

deploy:
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  - helm upgrade --install postgresql bitnami/postgresql -f postgresql/values.yml --version 10.16.2
  - helm upgrade --install kafka bitnami/kafka -f kafka/values.yml --version 14.5.0
  - okteto build -t okteto.dev/result:${OKTETO_GIT_COMMIT} result
  - helm upgrade --install result result/chart --set image.tag=${OKTETO_GIT_COMMIT}
  - okteto build -t okteto.dev/vote:${OKTETO_GIT_COMMIT} vote
  - helm upgrade --install vote vote/chart --set image.tag=${OKTETO_GIT_COMMIT}
  - okteto build -t okteto.dev/worker:${OKTETO_GIT_COMMIT} worker
  - okteto build -t okteto.dev/worker:dev --target dev worker
  - helm upgrade --install worker worker/chart --set image.tag=${OKTETO_GIT_COMMIT}

dev:
  result:
    command: nodemon server.js
    sync:
      - result:/app
    persistentVolume:
      enabled: false
  vote:
    command: mvn spring-boot:run
    sync:
      - vote:/app
    forward:
      - 5005:5005
    persistentVolume:
      enabled: false
  worker:
    image: okteto.dev/worker:dev
    command: bash
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    sync:
      - worker:/app
    forward:
      - 2345:2345
    persistentVolume:
      enabled: false
```

when I run "okteto up --deploy --build worker" it fails with the following message:
```
 x  Error building dev image: '--build' argument given but there is no Dockerfile
    Find additional logs at: /Users/ramiro/.okteto/rberrelleza/worker/okteto.log
```

The image is defined in the manifest, and `okteto build worker-dev` works successfully.  Why does it fail when running 'okteto up  --build worker-dev'?
