### ISSUE TITLE
okteto build and okteto up parse the manifest differently

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2689]
**Describe the bug**
I have this manifest:
``` 
build:
  todo-list
  
deploy:
  - cd manifest; kustomize edit set image okteto.dev/todo-list=okteto.dev/todo-list:${OKTETO_GIT_COMMIT}
  - kubectl apply -k manifest
dev:
  todo-list:
    image: okteto/golang:1
    command: bash
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    volumes:
    - /go/pkg/
    - /root/.cache/go-build/
    sync:
    - .:/app
    forward:
    - 2345:2345

```

When I run `okteto build`, the command ends successfully. But when I run ` okteto up`, I get this:
```
Invalid manifest:
    - line 2: cannot unmarshal !!str `todo-list` into model.ManifestBuild
    See https://okteto.com/docs/reference/manifest/ for details
``` 

Why do I get two different behaviors for the same manifest? Isn't ` up` simply calling ` build` internally for the build phase?

- OS: macOS
- Version okteto version 2.3.0-rc.1
