### ISSUE TITLE
User friendly errors when the yaml file can't be deserialized

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2690]
**Describe the bug**
If I have a badly formatted okteto.yml, I get this error:

```
Invalid manifest:
    - line 2: cannot unmarshal !!str `todo-list` into model.ManifestBuild
    See https://okteto.com/docs/reference/manifest/ for details
```

`model.ManifestBuild` and `!!str`  are not concepts that a regular user would understand. Is it possible to parse that error and show something more user friendly? (e.g. " cannot unmarshal line 2 into a `build` object. See https://www.okteto.com/docs/reference/manifest/#build-object-optional for reference")

- OS: macOS
- Version okteto version 2.3.0-rc.1 

**Additional context**
This is the manifest:
``` 
build:
  todo-list
  
deploy:
  - cd manifest; kustomize edit set image okteto.dev/todo-list=okteto.dev/todo-list:${OKTETO_GIT_COMMIT}
  - kubectl apply -k manifest
dev:
  todo-list:
    image: okteto/golang:1
    command: bash
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    volumes:
    - /go/pkg/
    - /root/.cache/go-build/
    sync:
    - .:/app
    forward:
    - 2345:2345
```
