### ISSUE TITLE
Deploying from the UI then okteto up doesn't find built images

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2692]
**Describe the bug**
When deploying from UI the images are built with the SHA of the image instead of the `:okteto` or `:okteto-with-volumes` tag. When running `okteto up` and we try to load env variables from the images it fails because it doesn't have the tags created

**To Reproduce**

1. Deploy from the UI https://github.com/okteto/microservices-demo/blob/main/okteto.yml
2. Wait to be fully deployed
3. Run `okteto up worker` on that repo 

**Expected behavior**
All the images should be already built and no error should be returned

**Desktop (please complete the following information):**

- OS: Macos
- Version 2.2.2

**Comment by pchico83** [comment]
@jLopezbarb `okteto up` should also build dev images if they don't exist, right?

**Comment by jLopezbarb** [comment]
Yes, but right now okteto up only builds images if they have a build section on the dev section:
 ```
dev:
  worker:
    image: ${OKTETO_BUILD_DEV_IMAGE}
    build: worker
    command: bash
    sync:
      - ./worker:/app
    forward:
      - 2345:2345
```

On the linked repo it can not detect the build section because we don't have a way to map the env var with the build section, which I think it's another issue that we should fix  
```
build:
  dev:
    context: worker
    target: dev
dev:
  worker:
    image: ${OKTETO_BUILD_DEV_IMAGE}
    command: bash
    sync:
      - ./worker:/app
    forward:
      - 2345:2345
```
