### ISSUE TITLE
Okteto up fails if build referenced from env var doesn't exists

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2693]
**Describe the bug**
If I have an `okteto.yml` v2 and I reference the build with an env var okteto doesn't build it

**To Reproduce**

1. Run okteto up on this okteto manifest
```
build:
  dev:
    context: worker
    target: dev
dev:
  worker:
    image: ${OKTETO_BUILD_DEV_IMAGE}
    command: bash
    sync:
      - ./worker:/app
    forward:
      - 2345:2345
```
2. Check that no build step is performed3. 

**Expected behavior**
I want that my dev image gets built

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.2.2

**Comment by pchico83** [comment]
We should build images that don't exist when getting the image SHAs to fill the `OKTETO_BUILD_XXX` envars

**Comment by pchico83** [comment]
This is specially relevant for manifests without `deploy` section like this one:
```
build:
  test-runner:
    target: ci
    args:
      - BUNDLE_GEM__FURY__IO=$BUNDLE_GEM__FURY__IO
dev:
  test-runner:
    autocreate: true
    image: ${OKTETO_BUILD_TEST_RUNNER_IMAGE}
    command: bundle exec rake db:create && bash
    sync:
      - .:/app
```
