### ISSUE TITLE
`okteto deploy --build` isn't redeploying my image if using volume mounts

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2700]
**Describe the bug**
If I use this compose file:

```
  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./models:/app/models
    - ./data:/app/data
    - ./helper:/app/helper
    - ./krg_address.db:/app/krg_address.db
    - ./users_db.py:/app/users_db.py
    command: ["rasa", "run","-m models", "--enable-api", "--cors",""*"", "-p 5006"]
    ports:
    - '5006:5006'
    public: true
    networks:
    - all
```

the service rasa-server isn't redeployed on each change.    

**Additional context**
Seems like we are deploying the image `okteto.dev/callbotkz-rasa-actions-server:okteto-with-volume-mounts` instead of the sha256 of that tag
