### ISSUE TITLE
Global port forwards in okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2709]
**Is your feature request related to a problem? Please describe.**
I have an okteto manifest with several dev containers. In every dev container, I need to expose my database ports to access my database on localhost. This makes it impossible to run two dev containers in parallel because of port collisions.

This problem is especially relevant when using hybrid development with `reverse` because I need to be able to access all my third-party dependencies on localhost.

**Describe the solution you'd like**
A section in the okteto manifest for global forwards, something like this:

```
forward:
  - 6379:redis:6379
  - 27017:mongo:27017
  - 3306:mysql:3306
  - 9092:kafka:9092
dev:
  api:
    reverse:
      - 3000:3000

  frontend:
    reverse:
      - 8080:3000
```

instead of what we have today:
```
dev:
  api:
    forward:
      - 6379:redis:6379
      - 27017:mongo:27017
      - 3306:mysql:3306
      - 9092:kafka:9092
    reverse:
      - 3000:3000

  frontend:
      forward:
      - 6379:redis:6379
      - 27017:mongo:27017
      - 3306:mysql:3306
      - 9092:kafka:9092
      reverse:
          - 8080:3000
```

Any `okteto up` command will enforce the global forwards are working. 

**Additional context**
In other to avoid running a daemon in the developer machine, `okteto up` could run a goroutine to check if the global forwards are running, and create them otherwise. It requires a goroutine in a loop because if an `okteto up` creates the global forwards, then there is a second `okteto up`, and then, the first `okteto up` exits, the second `okteto up` should regenerate the global forwards.

Also, port collisions should be ignored when another `okteto up` process is running the same okteto manifest, but if the port is in-use by another program, `okteto up` should fail.
