### ISSUE TITLE
Nil pointer if `depends_on` refers to a non existing service

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2716]
**Describe the bug**
Run `okteto deploy` with this compose file:
```
services:
  nginx:
    image: nginx
    depends_on:
      - db
```

and you will get:
```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Expected behavior**
Ideally, if the dependency exists in kubernetes (because it was created outside of the compose file), we could wait for it to be ready. But I would go with simplicity and show a proper error in this case while deserializing the compose file
