### ISSUE TITLE
Support `depends_on` for services in different stacks

### ISSUE THREAD

**Issue by willem-i-am** [okteto/okteto#2786]
Okteto 2.0 introduced `dependencies` so a repo can depend upon another repo's stack file being deployed first.

So let's say `repo-b` has a dependency on `repo-a` - so `repo-b`'s `okteto.yml` looks like this:

```
name: repo-b
dependencies:
  dev:
    repository: https://github.com/repo-a
    manifest: okteto.yml
    branch: main
deploy:
  - okteto deploy -f docker-compose.yml
```

It would be nice if the services in `repo-b`'s stack file, `docker-compose.yml`, could use the `depends_on` argument for services defined in `repo-a`'s stack file.

So the service in `repo-b` will wait until the service in `repo-a` is running, and if the service is not defined in `repo-a` then `okteto deploy` will throw an error.
