### ISSUE TITLE
My `build` section is gone if using the compose extended notation

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2795]
**Describe the bug**
My build section is ignored by `okteto deploy` with this manifest:
```
build:
  api:
    context: .

deploy:
  compose: mongodb-compose.yml
  commands:
    - name: Deploy API
      command: helm upgrade --install movies-api oci://registry.pablo.dev.okteto.net/okteto/movies-api --version 0.1.0 --set image=${OKTETO_BUILD_API_IMAGE}
```

Note that `okteto build` builds the image, but `okteto deploy` is not injecting the `OKTETO_BUILD_API_IMAGE` envvar.

Looks like it's related to using the `compose` field, if I delete it, my build section works with `okteto deploy`:
```
build:
  api: .

deploy:
  - name: Configure Helm with Okteto Registry
    command: echo "${OKTETO_TOKEN}" | helm registry login registry.pablo.dev.okteto.net -u ${OKTETO_USERNAME} --password-stdin
  - name: Pull Helm Chart from Okteto Registry
    command: helm pull oci://registry.pablo.dev.okteto.net/okteto/movies-api --version 0.1.0
  - name: Deploy API
    command: helm upgrade --install movies-api oci://registry.pablo.dev.okteto.net/okteto/movies-api --version 0.1.0 --set image=${OKTETO_BUILD_API_IMAGE}
```
