### ISSUE TITLE
Selecting multiple deployment

### ISSUE THREAD

**Issue by ujwaldhakal** [okteto/okteto#2823]
**Describe the bug**
I have two deployments that uses the same docker image. One handles the main API request while another one is used for background queue processing. When I try to select two deployments

```

selector:
  app.kubernetes.io/name: 'test'
```

 it complains about `Found '2' deployments for labels 'app.kubernetes.io/name=test instead of 1
`
**To Reproduce**

1. select multiple pods by using selector label
2. try running `okteto up`

**Expected behavior**
Synching multiple deployments with same image

**Comment by ujwaldhakal** [comment]
Thanks, @pchico83 for the answer.  I have two deployment one was `api` and another was `worker` as per your services documentation I came up with something like this

```
name: api
command: "php-fpm"
container: php
sync:
  - .:/var/www/html
  - $HOME/.composer:/root/.composer
persistentVolume:
  enabled: false

services:
  - name: worker
    container: php
    sync:
      - ./:/var/www/html
```
While using this I was able to see both kubernetes pod name was updated by something like api-okteto-124asf worker-okteto-124zxv but the file synchronization was only hapening for api deployment not the worker deployment which was inside the services.  So in the documentation it is written that services should be used for multiple containers does this mean multiple containers inside same pod or it is talking about multiple pod containers?


However with another approach I was able to make things work with the following configs

dev:
    api:
        name: api
        container: php
        sync:
          - .:/var/www/html
        persistentVolume:
          enabled: false
    worker:
        name: worker
        container: php
        sync:
          - .:/var/www/html
        persistentVolume:
          enabled: false

The only problem with this approach is I need two terminal session to run them. If we could have been able to sync both deployment from single command from okteto it would have been easier.
