### ISSUE TITLE
manifest option in dependencies is ignored 

### ISSUE THREAD

**Issue by alexissellier** [okteto/okteto#2825]
**Describe the bug**

The `manifest` option inside the declaration of a dependency is ignored and therefore only the manifest at the base folder is used.

**To Reproduce**
With this manifest
```
dependencies:
  grafana:
    repository: https://github.com/ankorstore/poc-okteto-dependencies
    manifest: okteto.yml
    branch: monitoring
    wait: true
  base:
    repository: https://github.com/ankorstore/poc-okteto-dependencies
    manifest: ./base/okteto.yml
    branch: monitoring
    wait: true
```
The `./base` is ignored and my dependency is using the manifest at the base directory.

This is the content of the configmap in my namespace 

```
$ k get cm/okteto-git-base -o yaml
apiVersion: v1
data:
  actionName: 6249acfd-5cd8-4455-a3dc-8a38ac3b0b76
  branch: monitoring
  commitSha: ""
  fallbackRepository: ssh://git@github.com/ankorstore/poc-okteto-dependencies
  filename: ""
  githubCommentId: ""
  icon: ""
  name: base
```
```
$ k get cm/okteto-git-grafana -o yaml
apiVersion: v1
data:
  actionName: 8e9db9a1-f441-4599-891a-25dbade57f66
  branch: monitoring
  commitSha: ""
  fallbackRepository: ssh://git@github.com/ankorstore/poc-okteto-dependencies
  filename: ""
  githubCommentId: ""
  icon: ""
  name: grafana

```

**Expected behavior**
The full path is used to fetch my manifest

**Desktop:**

- OS: Arch Linux
- Okteto cli version: okteto version 2.3.2 
- Okteto entreprise chart version :  helm.sh/chart: okteto-enterprise-0.13.0
- Application verison 1.12.132-4aadd0bc
