### ISSUE TITLE
Run commands in different context resource

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2834]
**Is your feature request related to a problem? Please describe.**
I want to be able to run commands on okteto deploy in different contexts and namespaces

**Describe the solution you'd like**
I want to be able to run them in a way like this:
``` yaml
deploy:
  - name: Deploy on default namespace
    command: kubectl apply -f k8s.yml
  - name: Deploy on different namespace
    command: kubectl apply -f k8s.yml
    namespace: another-namespace
```

**Describe alternatives you've considered**
Right now if I want to deploy a compose file and commands, they will run on the same namespace but it can happen that I want to deploy some resources on another namespace
