### ISSUE TITLE
okteto up doesn't consider the context of the image when building the path to the Dockerfile

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2874]
**Describe the bug**
If I have an image defined like this on the manifest:
```
build:
  # Dev image for the web service
  web-dev:
    context: web
    target: dev
```

`okteto build web-dev` will work correctly . `okteto up web`, on the other hand` will fail to build the image with this error:

```
 x  The image 'okteto.dev/node-compose-getting-started-web-dev:okteto' doesn't exist and can't be build
```
