### ISSUE TITLE
endpoints from the manifest missing name

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2877]
**Describe the bug**
If I have an `okteto.yml` like the following one and I run okteto deploy with it will fail because the endpoint doesn't have any name:
```yaml
deploy:
  compose:
    file: docker-compose.yaml
  endpoints:
  - path: /
    service: web
    port: 8080
  - path: /api
    service: api
    port: 3000
```

**To Reproduce**

1. Copy the okteto manifest above
2. Copy the following `docker-compose`:
```yaml
services:
  api:
    image: alpine
    ports:
    - 3000:3000
  web:
    image: alpine    
    ports:
    - 8080:8080
```
3. Run `okteto deploy`

**Expected behavior**
It should create the endpoints correctly

**Desktop (please complete the following information):**
- Version 2.4.1
