### ISSUE TITLE
okteto up does not understand docker-compose env_file list

### ISSUE THREAD

**Issue by ajrpayne** [okteto/okteto#2936]
In docker-compose.yml

```
env_file:
  - "${WEB_VARS}"
  - "${WEB_VARS2}"
```

In .env

```
WEB_VARS=./web-vars.env
WEB_VARS2=./web-vars2.env
```

In ./web-vars.env

```
DD_ENV=development
```

In ./web-vars2.env

```
DD_ENV2=development2
```

docker-compose -f docker-compose.yml config

```
environment:
  DD_ENV: development
  DD_ENV2: development2
```

okteto up
 x  Open {WEB_VARS2}=: no such file or directory

**Comment by jLopezbarb** [comment]
Hi @ajrpayne, I was not able to reproduce the issue. Can you provide more information about the issue like the CLI version you are using (`okteto version`) or if you have already a secret with key `WEB_VARS`.

Here is the scenario that I tested: 
1. Create the following files:
`.env` file:
```bash
WEB_VARS=./web-vars.env
WEB_VARS2=./web-vars2.env
```
`web-vars.env` file:
```bash
DD_ENV=development
```
`web-vars2.env` file:
```bash
DD_ENV2=development2

```
`docker-compose.yml` file:
```yaml
services:
  app:
    image: alpine
    command: printenv
    env_file:
      - "${WEB_VARS}"
      - "${WEB_VARS2}"
    volumes:
      - .:/usr/src
```
2. Run `okteto up`
3. See that the environment variables are the expected ones
