### ISSUE TITLE
Okteto down selector should only show activated dev environment.

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2946]
**Describe the bug**
If I have 10 dev environments and I'm currently with two of them in development mode (two services `okteto up`) I'd expect that `okteto down` selector only shows the dev environments that are now on development mode and hide the other ones

**To Reproduce**

1. Create the following `docker-compose.yml`
``` yaml
services:
  svc1:
    image: busybox
    volumes:
      - .:/usr/src
  svc2:
    image: busybox
    volumes:
      - .:/usr/src
  svc3:
    image: busybox
    volumes:
      - .:/usr/src
```
2. Run `okteto up svc1`
3. Run `okteto up svc2` on another terminal
4. Run `okteto down` on another terminal
5. See that the selector has svc1, svc2, and svc3

**Expected behavior**
I'd expect that `okteto down` selector only shows the services that are on development mode.

**Desktop (please complete the following information):**

- Version 2.4.2
