### ISSUE TITLE
init creates the wrong build context and docker file path

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2947]
**Describe the bug**
`okteto init` creates the build section wrong. It creates:
``` yaml
build:
  api:
    context: api
    dockerfile: api/Dockerfile
    image: jlopezbarb/movies-api:1.0.0
```
instead of:
``` yaml
build:
  api:
    context: api
    dockerfile: Dockerfile
    image: jlopezbarb/movies-api:1.0.0
```
**To Reproduce**

1. Clone [movies-with-helm](https://github.com/okteto/movies-with-helm)
2. Run `cd movies-with-helm`
3. Run `okteto init`
4. See that okteto.yml has been generated wrong

**Expected behavior**
I'd expect that the generated manifest was created correct

**Desktop (please complete the following information):**

- Version 2.4.2
