### ISSUE TITLE
Optimize build process when context for images do not exist

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2964]
**Is your feature request related to a problem? Please describe.**
While debugging https://github.com/okteto/okteto/issues/2626#issuecomment-1174879585 found that, if the context of some of the images declared to be built at the okteto manifest do not exist, this will fail when it gets to that image.

**Describe the solution you'd like**
We should check it the context of all images to be built, are valid, before starting to build all the images

**Comment by jLopezbarb** [comment]
@teresaromero should this manifest work to reproduce it if we run `okteto build`
```yaml
name: test
build:
  not-found:
    context: this-folder-no-exists
```

**Comment by teresaromero** [comment]
What i tried to express was that:

```
name: test
build:
  not-found:
    context: this-folder-no-exists
  found:
    context: this-exists
```

when the build process starts, found will be build and not-found will trigger an error, now imagine 4 found and 1 not found, so i think we should prevent this and build the found and warn that some are not found so the process is not broken because of this not found. Not sure i've express myself?
