### ISSUE TITLE
Service is running but not listening error

### ISSUE THREAD

**Issue by mstrYoda** [okteto/okteto#2974]
**Describe the bug**

I deploy a golang application using okteto-cli. The Kubernetes manifests are the same as the given [example in here](https://github.com/okteto/go-getting-started).

Even though the okteto up run successfully, I could not access my service due to "Service is running but not listening
Error: 502
Your service <name>/api is not listening on port 8080." error.

**To Reproduce**

1. copy the given files
2. run `okteto up`

**Expected behavior**
Access to service successfully.

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.5.2

**Additional context**

`okteto version`: okteto version 2.5.1

main.go :

```
package main

import "net/http"

func main() {

	http.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		rw.Write([]byte("hello okteto"))
	})

	http.ListenAndServe("0.0.0.0:8080", nil)
}
```

deployment.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: okteto.dev/golang-poc
        name: golang
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  ports:
  - name: "api"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    dev.okteto.com/generate-host: api
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
```

Dockerfile:

```
FROM golang:1.18-alpine3.14 as builder

WORKDIR /app

ENV CGO_ENABLED=0
ENV GOOS=linux

COPY . .

FROM alpine

COPY --from=builder /app /app

EXPOSE 8080

CMD ["./app/main"]
```

okteto.yml

```
name: okteto-golang

# The build section defines how to build the images of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#build
build:

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_API_REGISTRY: image registry
  #  - OKTETO_BUILD_API_REPOSITORY: image repo
  #  - OKTETO_BUILD_API_IMAGE: image name
  #  - OKTETO_BUILD_API_TAG: image tag
  api:
    image: okteto.dev/golang-poc

# The deploy section defines how to deploy your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#deploy
deploy:
  - kubectl apply -f deployment.yml
  
# The dependencies section defines other git repositories to be deployed as part of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#dependencies
# dependencies:
#   - https://github.com/okteto/sample


# The dev section defines how to activate a development container
# More info: https://www.okteto.com/docs/reference/manifest/#dev
dev:
  api:
    image: okteto.dev/golang-poc
    command:
      - sh
    sync:
      - .:/app
    forward:
      - 8080:8080

```
