### ISSUE TITLE
Okteto rebuilds image always without specifying `--build`

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2995]
**Describe the bug**
Okteto rebuilds the image always without specifying the `--build` flag if the image tag specified by the user is not using the default okteto tag. 

**To Reproduce**

1. Create this okteto stack:
```yaml
services:
  test:
    image: okteto.dev/test:dev
    build:
      context: .
```
2. Create this okteto manifest:
```yaml
deploy:
  compose: okteto-stack.yml

dev:
  test:
    command: ["bash"]
    sync:
      - .:/app
```
3. Run `okteto up` and see that is building image
4. Run `okteto up` again and see that rebuilds the image

**Expected behavior**
Second execution should be skipped due to image being built previously

**Desktop (please complete the following information):**
- OS: macOS
- Version 2.6

**Additional context**
Introduced in https://github.com/okteto/okteto/pull/2939
