### ISSUE TITLE
Panic on compose: depends on on non existent svc

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3001]
**Describe the bug**
Deploying a compose with a service that has a `depends_on` section causes a panic failure.
<img width="923" alt="Captura de pantalla 2022-08-12 a las 13 23 54" src="https://user-images.githubusercontent.com/25170843/184344533-f524cd3a-2dea-4022-9d40-a5470a72292a.png">

**To Reproduce**

1. Copy the following docker-compose:
```yaml
services:
  frontend:
    image: alpine
    ports:
      - 3000
    depends_on:
      - not-exist
```
2. Run `okteto deploy`
3. See error

**Expected behavior**
I want a clear error telling me what happened
