### ISSUE TITLE
Okteto CLI - connection seems very slow, app takes 3 minutes to start

### ISSUE THREAD

**Issue by marcindruzgala** [okteto/okteto#3007]
**Describe the bug**
Hi!

So we wanted to use your awesome CLI tool to enable cloud development on local machines with 'okteto up' to deploy our local files to the cluster. We've managed to achieve that but it seems that everything is super slow (I have worked with okteto also in my previous company and I didn't experience anything like that).

Yaml file is very simple and looks like that:

```yaml
name: identity-platform
image: okteto/dotnetcore:6
command: ["dotnet", "watch", "--project", "IdentityPlatform", "--", "run", "--configuration", "Debug", "--launch-profile", "okteto"]
workdir: /src
namespace: dev-marcin
remote: 2222
forward:
  - 8080:80
  - 5443:rds-aws:5432
  - 6380:dev-marcin-redis-master:6379
persistentVolume:
  enabled: false
```

Okteto is quite fast to replace the deployment and it shows the information about context, namespace and forwarded ports but then execution of the command takes 3-5 minutes. The same command takes more or less few seconds locally so it's not like the application takes so long to start :)

Any ideas what that might be?

**Desktop (please complete the following information):**

- OS: mac M1 Monterey 12.5 (tested also on windows 10 - same result)
