### ISSUE TITLE
`okteto build` is not getting my okteto secrets

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3044]
**Describe the bug**
I have an okteto secret named `TEST_SECRET` and the following okteto manifest:
```
build:
  test:
    context: .
    args:
      - TEST_SECRET=${TEST_SECRET}
```
but `TEST_SECRET` is not getting its value when running `okteto build`. It does when running `okteto deploy --build` or if `okteto up` builds the images, but not for `okteto build`.     

**To Reproduce**
Create the following files:

`okteto.yml`:
```
build:
  test:
    context: .
    args:
      - TEST_SECRET=${TEST_SECRET}

deploy:
  - echo "fake deploy"
```

`Dockerfile`:
```
FROM nginx

ARG TEST_SECRET

RUN echo "TEST_SECRET: $TEST_SECRET" && sleep 10
```

`okteto deploy --build` replaces `TEST_SECRET` but `okteto build` doesn't

**Additional context**
The Okteto CLI queries okteto secrets at the beginning of command execution. We are probably missing this for the `okteto build` command
