### ISSUE TITLE
Support `namespace` field in the extended `dependencies` notation

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3048]
**Is your feature request related to a problem? Please describe.**
I want to automate the deployment of a dependency always in the same namespace, because this is a shared namespace by all my team members.

**Describe the solution you'd like**
Support `namespace` in the `dependencies` extended notation, something like this:

```
dependencies:
  postgresql:
       repository: https://github.com/postgress
       wait: true
       namespace: integration
```
