### ISSUE TITLE
okteto deploy should not fail if deploy section is empty

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3065]
**Describe the bug**
Right now we are failing when an `okteto manifest v2` with an empty deploy section is deployed. We should be showing an information message linking [the deploy docs](https://www.okteto.com/docs/reference/manifest/#deploy-string-optional) and a message indicating that there is nothing to deploy

**To Reproduce**

1. Create the following okteto manifest:
```yaml
build:
  a:
    context: .
  b:
    context: .
  c:
    context: .
    dockerfile: a.Dockerfile
```
1. Run `okteto deploy`
1. See error
<img width="547" alt="Captura de pantalla 2022-09-02 a las 14 55 13" src="https://user-images.githubusercontent.com/25170843/188150378-f5a853bb-de63-475a-b08a-3e39cdfa1009.png">

**Expected behavior**
I don't want to fail, only a message indicating that the deploy section is empty and a link to the docs

**Desktop (please complete the following information):**

- Version 2.6.0
