### ISSUE TITLE
Deprecate okteto manifest v1

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3066]
**Is your feature request related to a problem? Please describe.**
Okteto CLI 2.0 support the [okteto manifest v2](https://www.okteto.com/docs/reference/manifest/) which supersedes the functionality of the okteto manifest v1. Most of our users have already migrated to the manifest v2, and the manifest v1 isn't documented in the [okteto docs](https://github.com/okteto/docs) since June 2002.

**Describe the solution you'd like**
Show a warning when `okteto up` is running versus an okteto manifest v1. The warning show indicate that support for manifest v1 will be removed in Okteto CLI 3.0. Also show an information message with a link to the migrating from manifest [v1 to v2 tuturial](https://www.okteto.com/docs/reference/manifest-migration/).

**Additional context**
Add a metric to track, on each `okteto up` event, if the user is using manifest v1, v2 or a plain compose file.

**Comment by jLopezbarb** [comment]
Are we deprecating the use of the manifest v1 completely or are we still planning to use it on the `dependencies` field? 
Example:
```yaml
build:
  a:
    context: .
dependencies:
   - frontend/okteto.yml
   - backend/okteto.yml
deploy:
  - kubectl apply
# dev is not needed because they are specified by the dependencies field
```
