### ISSUE TITLE
Compose is not taking in consideration `depends_on` while building

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3067]
**Describe the bug**
I want that okteto CLI build my compose images taking in count the `depends_on` field on the services.

**To Reproduce**

1. Use this compose and Dockerfile:
`docker-compose.yml `
```yaml
services:
  a: 
    build: .
    dockerfile: a.Dockerfile
    depends_on: b
  b:
    build: .
    dockerfile: b.Dockerfile
```
`a.Dockerfile`
```Dockerfile
FROM alpine

ARG OKTETO_BUILD_B_IMAGE

RUN echo hola "${OKTETO_BUILD_B_IMAGE}"
```
`b.Dockerfile`
```Dockerfile
FROM alpine
```
1. Run `okteto build -f docker-compose.yaml`
1. See that is not injecting build args

**Expected behavior**
I want to inject the build args on the build step

**Desktop (please complete the following information):**
- Version 2.6.0
