### ISSUE TITLE
`OKTETO_BUILD_XXX` envaars are not injected on `okteto deploy --build`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3074]
**Describe the bug**
`OKTETO_BUILD_XXX` envvars are not injected when running `okteto deploy --build` and having a compose file in the `deploy` section.

**To Reproduce**
Add the following file to the `okteto/movies` repo:
```
version: '3'
services:
  db_postgres_products:
    image: postgres:11
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
      POSTGRES_DB: products
    ports:
      - "5432:5432"
```   

and update the okteto manifest to have:
```
deploy:
  compose: docker-compose.yaml
  commands:
  - name: Echo
    command: env | grep OKTETO
  ...
```       

You will see that `OKTETO_BUILD_XXX` envars are not available.
