### ISSUE TITLE
I want to redeploy my stack without downtime

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3083]
**Describe the bug**
If I redeploy my `okteto stack` I want to have 0 downtimes but since the deployments created have the recreate update strategy, I can't 

**To Reproduce**

1. Copy the following `docker-compose.yml`
```yaml
services:
  app:
    image: python:alpine
    entrypoint: python -m http.server 8080
    ports:
      - 8080:8080
```
2. Run okteto deploy
3. Change the entrypoint to `python -m http.server 8081`
4. Run okteto deploy to redeploy
5. See that the pod is recreated

**Expected behavior**
I want to have 0 downtime while redeploying a compose/stack

**Desktop (please complete the following information):**

- Version 2.6.0
