### ISSUE TITLE
$OKTETO_BUILD_* variables not available for use in build section of manifest

### ISSUE THREAD

**Issue by cowgod** [okteto/okteto#3089]
**Describe the bug**
The $OKTETO_BUILD_* variables are not available for use in the `build` section of the manifest. I would like to be able to pass build arguments to  my Dockerfile using the values of a previously-built service, but they don't seem to be available at that point.

**To Reproduce**

1. Create `okteto.yaml` with the following contents:
```
build:
  service-a:
    dockerfile: Dockerfile.a
  service-b:
    dockerfile: Dockerfile.b
    depends_on: service-a
    args:
      SOURCE_REGISTRY: $OKTETO_BUILD_SERVICE_A_REGISTRY
      SOURCE_REPOSITORY: $OKTETO_BUILD_SERVICE_A_REPOSITORY
      SOURCE_TAG: $OKTETO_BUILD_SERVICE_A_TAG
```
2. Create `Dockerfile.a` with the following contents:
```
FROM bash:latest

RUN echo "IMAGE A" > /root/output_a.txt

ENTRYPOINT ["tail", "-f", "/dev/null"]
```
3. Create `Dockerfile.b` with the following contents:
```
FROM bash:latest

ARG SOURCE_REGISTRY="(DEFAULT_REGISTRY)"
ARG SOURCE_REPOSITORY="(DEFAULT_REPOSITORY)"
ARG SOURCE_TAG="(DEFAULT_TAG)"

RUN echo "IMAGE B" > /root/output_b.txt \
 && echo "SOURCE_REGISTRY=$SOURCE_REGISTRY" >> /root/output_b.txt \
 && echo "SOURCE_REPOSITORY=$SOURCE_REPOSITORY" >> /root/output_b.txt \
 && echo "SOURCE_TAG=$SOURCE_TAG" >> /root/output_b.txt \
;

ENTRYPOINT ["tail", "-f", "/dev/null"]
```
4. Run a build using at least version 2.7.0 of Okteto CLI:
```
/usr/local/bin/okteto-2.7.0-beta.2 build --log-level debug
```
5. Bring up a pod in the Okteto cluster using the new image. For example, with the following manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: web
      image: registry.<OKTETO_DOMAIN>/<NAMESPACE>/okteto-service-b:okteto
```
6. Examine the contents of the file written during the build process:
```
kubectl -n <NAMESPACE> exec -it pod/test -- cat /root/output_b.txt
```

**Expected behavior**
The file should contain the following output, indicating that the build arguments were set correctly during the build process:
```
IMAGE B
SOURCE_REGISTRY=registry.<OKTETO_DOMAIN>
SOURCE_REPOSITORY=<NAMESPACE>/okteto-service-a
SOURCE_TAG=sha256:3f0f4c903f0f61cd2a8cdcd0f82cd0e23521ab2637e495bba176e8f1c485d44e
```

**Desktop (please complete the following information):**

- OS: macOS
- Version: Ventura 13.0 beta

**Additional context**
The `$OKTETO_BUILD_*` values **are** available as build arguments within the image itself, if I add lines like:
```
ARG OKTETO_BUILD_SERVICE_A_REGISTRY
```
to the Dockerfile. But I would like to be able to use a standalone Dockerfile within Okteto without having to rewrite the Dockerfile to incorporate the Okteto-specific variables. This requires being able to pass in the argument names that it's expecting by defining them in the Okteto manifest, as described above.
