### ISSUE TITLE
Add a timeout for specific dependencies

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3146]
**Is your feature request related to a problem? Please describe.**
I have a bunch of remote dependencies, and I want to specific a custom timeout for each of them

**Describe the solution you'd like**
I would like a new field on the dependencies section that adds the ability to set the timeout for the dependencies:
```yaml
dependencies:
  - api:
     repository: https://github/test/api
     timeout: 10m
  - frontend:
     repository: https://github/test/frontend
     timeout: 5m
```

**Additional context**
If the timeout is not specified in the dependency, we should be using the timeout flag of the deploy command
If the timeout is not specified in the dependency nor in the timeout flag. We should be using the `OKTETO_TIMEOUT` environment variable
