### ISSUE TITLE
The sample of private endpoints + docker compose is broken

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3182]
**Describe the bug**
I am adding a label to define my private endpoint, but it's not working. My endpoint is still public.

**To Reproduce**
Deploy this compose:
```
services:
  api:
    labels:
      dev.okteto.com/private: "true"
    image: nginx
    ports:
      - "8080:80"
```
with `okteto deploy`.
The endpoint is public.    
**Expected behavior**
The endpoint should be private

**Additional context**
We should populate the labels/annotations in the compose service to every resource create by okteto, including the Ingress object created for the endpoint. This would fix the issue
