### ISSUE TITLE
Error building: file with no instructions?

### ISSUE THREAD

**Issue by scheung38** [okteto/okteto#3218]
*Describe the bug**

Error building service ‘django’: error building image ‘sample_cookiecutter_local_django’: build failed: failed to solve: file with no instructions?

**To Reproduce**

okteto deploy --build --wait

okteto.yml

```
build:
  django:
    image: sample_cookiecutter_local_django
    context: .
deploy:
  - kubectl apply -f manifest
```

production.yml

```
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sample_cookiecutter_production_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sample_cookiecutter_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - 5432:5432

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: sample_cookiecutter_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  ```

where manifest is folder that was created from

kompose --file production.yml -o $HOME/Documents/sample_cookiecutter/manifest convert  --volumes hostPath

**Expected behavior**
okteto cloud deploy of django app

**Desktop (please complete the following information):**

- OS: [e.g. macOS] MacOS 12.5
- kompose: 1.26.0 (40646f47)
- python: 3.9.9
**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)
