### ISSUE TITLE
Environment variables are not interpolated in the `dev.image` field

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3223]
**Describe the bug**
I want to be able to use the value  of an environment variable in the image name of my dev blocks:

```
dev:
  frontend:
    image: okteto.dev/frontend-dev:${GIT_COMMIT:-latest} # I always get latest even if I set GIT_COMMIT to something else
    command: bash
    sync:
      - frontend:/usr/src/app
```
When I run  `okteto deploy`, env vars are interpolated correctly for scripts executed on the `deploy` block. But when I run `okteto up`, env vas are not available to use as part of my image name.
