### ISSUE TITLE
Deploy external resource with `okteto deploy` command

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3267]
As a developer I want to be able to deploy the external resources I have defined in my okteto manifest, so I can use that information in the UI to have a full view of my application.

The idea is that `okteto deploy` command deploys all the external resources with the label `deployed-by`

## Acceptance criteria

- [ ] okteto deploy must deploy the external resources defined in the okteto manifest
- [ ] it should throw a warning if the cluster is not a cluster managed by okteto
- [ ] When creating the new external resource item the following fields must be created
  - [ ] `deployed-by` annotation could be present
  - [ ] `last-updated` annotation must be present
  - [ ] `id` is an Autogenerated UUID
  - [ ] `name` must be present
  - [ ] `creationTime` is present
  - [ ] `Endpoints` must present
  - [ ] `Notes` is present
    - [ ] `path` is present
    - [ ] `markdown` is present

**Comment by AdrianPedriza** [comment]
> As a developer I want to be able to deploy the external resources I have defined in my okteto manifest, so I can use that information in the UI to have a full view of my application.
> 
> The idea is that `okteto deploy` command deploys all the external resources with the label `deployed-by`
> 
> ## Acceptance criteria
> * [ ]  okteto deploy must deploy the external resources defined in the okteto manifest
> * [ ]  it should throw a warning if the cluster is not a cluster managed by okteto
> * [ ]  When creating the new external resource item the following fields must be created
>   
>   * [ ]  `deployed-by` annotation could be present
>   * [ ]  `last-updated` annotation must be present
>   * [ ]  `id` is an Autogenerated UUID
>   * [ ]  `name` must be present
>   * [ ]  `creationTime` is present
>   * [ ]  `Endpoints` must present
>   * [ ]  `Notes` is present
>     
>     * [ ]  `path` is present
>     * [ ]  `markdown` is present

to avoid misunderstandings, can you add an example of what the final result of an external resource item should look like?

**Comment by jLopezbarb** [comment]
This is a k8s file I've been using to test that the CRD is working:
```yaml
apiVersion: "dev.okteto.com/v1"
kind: External
metadata:
  name: UID generated by the CLI
spec:
  name: "test"
  notes:
    path: my-api.md
    markdown: aG9sYSBjb21vIGVzdGFzIG1pIG5vbWJyZSBlcyBqdWxpYW4=
  endpoints:
    - name: api
      url: localhost:8080
```
