### ISSUE TITLE
Add image to the deploy section

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3320]
As a user, I want to run my okteto deploy command if the image is set in the deploy section

The deploy section in the `okteto manifest` must have a new `image` field which is optional
```yaml
deploy:
  image: okteto/pipeline-runner:1.0.0
  commands:
  - name: Say hello
    command: echo "Hello world"
```

If `image` is set we must use a new interface that differentiates between the remote deployment and the local one.

```go
// names and methods are provisional
type DeployCommand interface {
	deploy()
}

type LocalDeployer struct {
	mockLocalObjects...
}

type RemoteDeployer struct {
  mockRemoteObjects...
}
```

### Acceptance criteria

- [ ] Parsing a manifest with the `deploy.image` field set don't throw an error
- [ ] Deploying local must continue working as before
- [ ] Common methods must not be duplicated
