### ISSUE TITLE
set external endpoint URL using OKTETO_ENV file

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3341]
After deploying the commands we must set the endpoints env variables to the correct `external.endpoint`

_Syntax_
```yaml
deploy:
  - echo "deploying commands"
  - echo "OKTETO_ENDPOINTS_DB_URL_MONGO=https://localhost:27017" >> OKTETO_ENV
external:
  db:
      endpoints:
      - name: mongo
         # url set to `https://localhost:27017`
      - name: mysql
         url: https://localhost:3306
```

# Acceptance criteria
- [ ] If OKTETO_ENV has not desired env we must fail
- [ ] External resource is able to get env value from `OKTETO_ENV` once deploy section has been executed
- [ ] Show a warning if a external resource is already set and `OKTETO_ENV` overwrites it
- [ ] Endpoints name must be unique lower cased.
