### ISSUE TITLE
Error building an image to resolve host volumes

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3366]
**Describe the bug**
A docker-compose like this is failing to build:
```
  db:
    image: postgres:12
    volumes:
      - ../../infrastructure/repository-sql/sql:/docker-entrypoint-initdb.d
```
 This is failing to deploy with a cryptic error. The prorblem is that ge generate a temporal dockerfile to copy the host volumes files but it's taking the wrong context because the host volume isn't in the current folder.

**Expected behavior**
I don't think a fix is worth here, I would show a clear error when the host volume is not in current folder
