### ISSUE TITLE
Segmentation fault when deploying a compose non existing service

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3367]
**Describe the bug**
Customers are reporting than:

```
okteto deploy -f ../docker/docker-compose.yaml service-doesn't-exist
```

throws a `SIGSEGV` exception

**Expected behavior**
A clear error saying that the service doesn't exist

**Comment by andreafalzetti** [comment]
I've tried deploying a non-existing service but I already get a nice message:
![Screenshot 2023-03-10 at 12 32 08](https://user-images.githubusercontent.com/2318450/224383797-0b9e392a-cdf9-4f43-8d23-28adca73add3.png)

I am using okteto version `2.11.1` and [this project](https://github.com/okteto/go-api-docker-compose/blob/main/docker-compose.yml).

I am wondering whether the user had an old CLI version, for example before this fix was released: https://github.com/okteto/okteto/pull/2956

One thing I've noticed, altough it's a slighlty different issue, is that if I define a new service in `docker-compose.yml` but I don't define its properties, it will throw a `SIGSEGV`.

![Screenshot 2023-03-10 at 12 35 17](https://user-images.githubusercontent.com/2318450/224384286-959a21d9-4d62-44bb-99c2-c430b8fb26e2.png)

```yaml
version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
  another-service:

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data:
```

@pchico83 if you spot I am missing something to reproduce the issue, please let me know. In the meantime I will have  a look at failing gracefully when the config is invalid.
