### ISSUE TITLE
`okteto destroy` Your token is invalid.

### ISSUE THREAD

**Issue by acelinkit** [okteto/okteto#3401]
**Describe the bug**
`okteto destroy` command returns an invalid token error when connecting to a kubernetes cluster.  `okteto up` and `okteto down` commands work without any issue.  

```
okteto destroy   
 i  Using default @ rancher-desktop as context
 x  Your token is invalid. Please run 'okteto context use rancher-desktop' and try again
 ```

**To Reproduce**
```
okteto kubeconfig
okteto context use rancher-desktop
okteto deploy
okteto down
okteto destroy
```

**Expected behavior**
Environment is destroyed.

**Desktop (please complete the following information):**
- Okteto: 2.12.1
- OS: MacOS 13.2
- Kubernetes: v1.25.3 via RancherDesktop

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)
okteto.yml
```
deploy:
  - kubectl apply -f k8s
dev:
  hello-world:
    image: okteto/golang:1
    command: bash
    sync:
      - .:/usr/src/app
```
