### ISSUE TITLE
remote deploy: okteto version shows a different version from the one I'm using

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3402]
**Describe the bug**
If I run a remote deploy and in the deploy section I run `okteto version`, the output differs from the one I'm running on my local machine

**To Reproduce**

1. Create the following okteto manifest:
```yaml
deploy:
  image: alpine
  commands:
  - okteto version
```
2. Run `okteto deploy`
3. Check that output is `okteto version docker`
4. Remove the image field from the okteto manifest:
```yaml
deploy:
  commands:
  - okteto version
```
5. Run `okteto deploy`
6. Check that output is `okteto version 2.13.0-beta.1`

**Expected behavior**
The output should be `okteto version 2.13.0-beta.1`

**Desktop (please complete the following information):**
- Version 2.13.0-beta.1

**Additional context**
We should be injecting the okteto binary that the user is using locally. This prevents  the user to have different behavior locally and deploying on remote
