### ISSUE TITLE
Building an image exports that image to the cache

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3424]
## Parent epic/feature

* Feature: [Pull-first Approach for Okteto Registry](https://www.notion.so/okteto/Pull-first-Approach-for-Okteto-Registry-6b669819844d4239bc16787989c620a3?pvs=4)

## Description

In order to optimize the builds so that if a previous image has already been created, we should cache the layers so that when the same build is called it always has the cache of the previous builded images. For this, when we build an image we must store the layers in the cache. This way the user could import from the image for other builds.

This issue seeks to always export the cache of the image built as `inline` type and with mode set to `min` ([as it's the only value that is available with inline](https://github.com/moby/buildkit#export-cache)).

We should add always the image that the user is using to the export cache option programatically(note that the user has already set an image in the `export_cache`):
```yaml
build:
  api:
    context: .
    dockerfile: Dockerfile
    export_cache: okteto.dev/my-app:cache
    image: okteto.dev/api:okteto
```

should become programatically:
```yaml
build:
  api:
    context: .
    dockerfile: Dockerfile
    export_cache:
    - okteto.dev/my-app:cache
    - okteto.dev/api:okteto
    image: okteto.dev/api:okteto
```

In order to do that we need to allow using a list in the `export_cache` field and modify the builder to export all the caches in the manifest

### Acceptance criteria

- [ ] `export_cache` field admits a list instead a single string
- [ ]  adds to `export_cache` field the needed values: always export cache to specified registry plus the one user has access to. 

##### Scenario 1: User can provide a list

1. Create a new namespace
2. Create the following manifest:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    export_cache:
    - okteto.dev/frontend:1.0.0
    - okteto.dev/frontend:2.0.0
```
3. Run the following build command: `okteto build` (this will export cache to `okteto.dev/frontend:1.0.0` and `okteto.dev/frontend:2.0.0` registry)
4. Add `cache_from` field pointing to same values used in `export_cache`:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - okteto.dev/frontend:1.0.0
    - okteto.dev/frontend:2.0.0
```
5. Create a new namespace
6. Run `okteto build` and check image is cached

##### Scenario 2 - User can provide an string (non breaking previous scenarios)

1. Create a new namespace
2. Create the following manifest:
``` yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    export_cache: okteto.dev/frontend:1.0.0
```
3. Run the following build command: `okteto build` (this will export cache to `okteto.dev/frontend:1.0.0`)
4. Add `cache_from` field pointing to same values used in `export_cache`:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - okteto.dev/frontend:1.0.0
```
5. Create a new namespace
6. Run `okteto build` and check image is cached

##### Scenario 1 - Always export what the user is building

1. Create a new namespace
2. Create the following manifest:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    export_cache:
    - okteto.dev/frontend:1.0.0
    image: okteto.global/frontend:1.0.0

```
4. Run the following build command: `okteto build` (This will export cache to `okteto.dev/frontend:1.0.0` and `okteto.global/frontend:1.0.0`)
5. Add `cache_from` field pointing to the global registry:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - okteto.global/frontend:1.0.0
```
7. Create a new namespace
8. Run `okteto build` and check image is using the cache properly
9. Modify again the manifest to:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - okteto.dev/frontend:1.0.0
```
7. Create a new namespace
8. Run `okteto build` and check image is using the cache properly

##### Scenario 2 - Always export what the user is building

1. Create a new namespace
2. Create the following manifest:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    image: myregistry/ns/frontend:1.0.0

```
4. Run the following build command: `okteto build` (This will export cache to `myregistry/ns/frontend:1.0.0`)
5. Add `cache_from` field pointing to the global registry:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - myregistry/ns/frontend:1.0.0
```
7. Create a new namespace
8. Run `okteto build` and check image is using the cache properly
