### ISSUE TITLE
Hybrid development: add mode field dev section

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3425]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-7fbd3a6a566145d3a4930d3c15fc642d?pvs=4)

## Description

We want our users to be able to develop in the most comfortable way possible. That is why we are going to add the option to develop following a hybrid approach. This means that instead of synchronizing the code and developing with the code living in the cluster, the code lives in local and through a reverse the connections are made.

This issue will try to add this new mode in a way that does not modify any of the functionality we have for the dev section. To do so, we will modify the way of making unmarshal of each of the dev by checking the value of the new mode field (sync, hybrid).

```yaml
dev:
  frontend:
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: frontend
    command: ["sh", "-c", "yarn start"]
    reverse:
      - 8080:8080
  api:
    mode: sync
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: api
    image: okteto/golang:1
    environment:
      - LOG_FORMATTER=text
    command: sh
    sync:
      - ./api:/usr/src/app
    forward:
      - 2345:2345
  producer:
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: producer
    image: okteto/golang:1
    command: sh
    sync:
      - ./producer:/usr/src/app
    forward:
      - 2345:2345
```

The only fields supported in the hybrid mode are:
- `reverse`
- `command`
- `environment`
- `forward`
- `selector`
- `workdir`

After serializing we need to convert the hybrid dev into a normal dev. This will allow us to continue using the same translation rules that are used in `sync` mode:
- Using a small image like busybox 
- Use an infinite command(`while true ; do continue ; done`)
- Use an empty sync folder.

### Tips:
- We could parse the dev section in two steps. The first one we unmarshal the `mode` and then 

## Acceptance Criteria

- [ ] `okteto up` continues working with a manifest without mode specified
- [ ] `okteto up` continues working if mode is `sync`
- [ ] `okteto up` tracks a new property that indicates the mode the user is developing  
- [ ] `okteto up` creates a new app that is running the small image with the infinite command

## Test strategy and scenarios

All the tests scenarios will use the yaml used below:
```yaml
dev:
  frontend:
    mode: hybrid
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: frontend
    command: ["sh", "-c", "yarn start"]
    reverse:
      - 8080:8080
  api:
    mode: sync
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: api
    image: okteto/golang:1
    environment:
      - LOG_FORMATTER=text
    command: sh
    sync:
      - ./api:/usr/src/app
    forward:
      - 2345:2345
  producer:
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: producer
    image: okteto/golang:1
    command: sh
    sync:
      - ./producer:/usr/src/app
    forward:
      - 2345:2345
```

#### Scenario 1
1. Copy the okteto manifest above
2. Create a folder named `producer` on the path
3. Run `okteto up producer`
4. It should work as before

#### Scenario 2
1. Copy the okteto manifest above
2. Create a folder `api` on the path
3. Run `okteto up api`
4. It should work as before
