### ISSUE TITLE
new `cache_from` logic when building an image

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3426]
## Parent epic/feature

* Feature: [Pull-first Approach for Okteto Registry](https://www.notion.so/okteto/Pull-first-Approach-for-Okteto-Registry-6b669819844d4239bc16787989c620a3?pvs=4)

## Description

In order to optimize the builds so that if a previous image has already been created, when building an image we will add to the `cache_from` field the appropriate registries according to the scenarios where we are. This implementation will not modify the manifest but internally it will take into account the proper registries to used them as cache when building an image.
## Acceptance criteria

- [ ] if global registry is active, adds in `cache_from` field a new entry pointing to global registry using current git commit (no matter if commit is dirty) 
- [ ] adds in `cache_from` field a new entry pointing to dev registry using `cache` as image tag.

#### Scenario 1: Global registry active

1. Create a new namespace
2. Create the following manifest:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    image: okteto.dev/frontend:1.0.0
```
3. Run the following build command: `okteto build` (this will use cache from `okteto.dev/frontend:cache` and `okteto.global/frontend:cache` registry)
4. Internally it transform the manifest to:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - okteto.global/frontend:cache
    - okteto.dev/frontend:cache
```

##### Scenario 2 - Global registry not active

1. Create a new namespace
2. Create the following manifest:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    image: okteto.dev/frontend:1.0.0
```
3. Run the following build command: `okteto build` (this will use cache from `okteto.dev/frontend:cache`registry)
4. Internally it transform the manifest to:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    cache_from:
    - okteto.dev/frontend:cache
```

##### Scenario 3 - Non okteto dev registry

1. Create a new namespace
2. Create the following manifest:
```yaml
build:
  frontend:
    context: frontend
    dockerfile: Dockerfile
    image: docker.io/my-user/frontend:1.0.0
```
3. Run the following build command: `okteto build`
4. Check that no cache is exported
