### ISSUE TITLE
Hybrid development: hybrid translations

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3443]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-7fbd3a6a566145d3a4930d3c15fc642d?pvs=4)

## Description

We want our users to be able to develop in the most comfortable way possible. That is why we are going to add the option to develop following a hybrid approach. This means that instead of synchronizing the code and developing with the code living in the cluster, the code lives in local and through a reverse the connections are made.

This issue aims to create the proper translations that will be needed to create the correct hybrid development. The translations are:
- Scalate to 0 the original deployment
- Set dev label (`dev.okteto.com`) to true
- Set previous replicas annotation(`dev.okteto.com/replicas`) to the previous replicas that the original deployment had
- Don't create new deployment (since we are going to launch the process locally)

### Tips:
- `okteto up` code is not well tested. Any code that is introduced and easy to test should be tested
- `okteto up` code should be working as it was previously. Creating an interface to distinguish between the different modes could be a good option

## Acceptance Criteria

- [ ] `okteto up` continues working with a manifest in `sync` mode
- [ ] `okteto up` doesn't create a new deployment in `hybrid` mode
- [ ] `okteto down` restores the original status of the application in `sync` mode
- [ ] `okteto down` restores the original status of the application in `hybrid` mode

## Test strategy and scenarios

All the tests scenarios will use the yaml used below:
```yaml
dev:
  frontend:
    mode: hybrid
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: frontend
    command: ["sh", "-c", "yarn start"]
    reverse:
      - 8080:8080
  api:
    mode: sync
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: api
    image: okteto/golang:1
    environment:
      - LOG_FORMATTER=text
    command: sh
    sync:
      - ./api:/usr/src/app
    forward:
      - 2345:2345
  producer:
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: producer
    image: okteto/golang:1
    command: sh
    sync:
      - ./producer:/usr/src/app
    forward:
      - 2345:2345
```

#### Scenario 1
1. Copy the okteto manifest above
2. Create a folder named `producer` on the path
3. Run `okteto up producer`
4. It should work as before

#### Scenario 2
1. Copy the okteto manifest above
2. Create a folder `api` on the path
3. Run `okteto up api`
4. It should work as before

#### Scenario 3
1. Copy the okteto manifest above
2. Create a folder `frontend` on the path
3. Run `okteto up frontend`
4. It should not create a new deployment
