### ISSUE TITLE
Hybrid development: Command runner

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3444]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-7fbd3a6a566145d3a4930d3c15fc642d?pvs=4)

### Depends on:

* #3425  

## Description

We want our users to be able to develop in the most comfortable way possible. That is why we are going to add the option to develop following a hybrid approach. This means that instead of synchronizing the code and developing with the code living in the cluster, the code lives in local and through a reverse the connections are made.

This issue aims to run the service that the user is trying to run in hybrid mode locally, creating the connections with the clusters specified by reverse/forward ports:
- The command must be run locally
- The command must have the `workdir` specified. If not specified the project `workdir` will be the one used
- The environment variables must be the same ones as if the command was run in the cluster. (Defined in the environment variables) 
- Anew field is added to the `up` metrics to specify which mode the user is using
- Only one `okteto up` can be running at the same time for the same service
- We should add env vars from:
  - main image. Inspect the image to retrieve the env vars
  - config map. 
  - okteto secrets
 

### Tips:
- `okteto up` command execution should be working as it was previously. Creating an interface that runs the command could be a good option 

## Acceptance Criteria

- [ ] `okteto up` continues working with a manifest in `sync` mode
- [ ] `okteto up` in `hybrid` mode runs locally with the env vars defined
- [ ] `okteto down` restores the original status of the application in `sync` mode
- [ ] `okteto down` restores the original status of the application in `hybrid` mode
- [ ] Add `okteto up` in `hybrid` e2e test

## Test strategy and scenarios

All the tests scenarios will use the yaml used below or any example but keep in mind to use the `sync` mode:
```yaml
dev:
  frontend:
    mode: hybrid
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: frontend
    command: ["sh", "-c", "echo KEY=$KEY && yarn start"]
    environment: 
      KEY: VALUE
    reverse:
      - 8080:8080
  api:
    mode: sync
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: api
    image: okteto/golang:1
    environment:
      - LOG_FORMATTER=text
    command: sh
    sync:
      - ./api:/usr/src/app
    forward:
      - 2345:2345
  producer:
    selector:
      app.kubernetes.io/part-of: okteto
      app.kubernetes.io/component: producer
    image: okteto/golang:1
    command: sh
    sync:
      - ./producer:/usr/src/app
    forward:
      - 2345:2345
```

#### Scenario 1
1. Copy the okteto manifest above
2. Create a folder named `producer` on the path
3. Run `okteto up producer`
4. It should work as before

#### Scenario 2
1. Copy the okteto manifest above
2. Create a folder `api` on the path
3. Run `okteto up api`
4. It should work as before

#### Scenario 3
1. Copy the okteto manifest above
2. Create a folder `frontend` on the path
3. Run `okteto up frontend`
4. Check that the okteto output prints KEY=VALUE before starting the yarn command
5. Check that the application connects with the rest of the application
