### ISSUE TITLE
`okteo deploy --remote` output isn't indented properly

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3456]
**Describe the bug**
When I run `okteto deploy --remote` the output loses the indentation and adds warning icons that doesn't happen with `okteto deploy` local execution.

**To Reproduce**

1. Clone the branch `debug` of https://github.com/okteto/movies-with-helm
1. Run `okteto deploy --remote`
1. The first lines look like this:
```
!  history.go:56: [debug] getting history for release movies
!  upgrade.go:142: [debug] preparing upgrade for movies
...
```
1. The final lines look like this:
```
# Source: movies/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: movies
labels:
helm.sh/chart: movies-0.1.0
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: movies
app.kubernetes.io/version: "1.0.0"
annotations:
dev.okteto.com/generate-host: "true"
spec:
rules:
- http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: frontend
port:
number: 80
- path: /api
pathType: Prefix
backend:
service:
name: api
port:
number: 8080
NOTES:
Success! Your application will be available shortly.
```

**Expected behavior**
The first lines look like this (same output than original command):

```
history.go:56: [debug] getting history for release movies
upgrade.go:142: [debug] preparing upgrade for movies
...
```

and the final lines look like this:

```
# Source: movies/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies
  labels:
    helm.sh/chart: movies-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: movies
    app.kubernetes.io/version: "1.0.0"
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080

NOTES:
Success! Your application will be available shortly.
```

**Additional context**
Double check the output is the same in the Okteto UI, with the same indentation, metadata, and warning symbols.
