### ISSUE TITLE
services with selector set detached label empty

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3484]
**Describe the bug**
Okteto doesn't set the name of the deployment in detached label if the service is under the `services` section

**To Reproduce**

1. Deploy https://github.com/okteto/movies-with-helm
1. Modify the `okteto.yml` to be:
```yaml
icon: https://apps.okteto.com/movies/icon.png

build:
  api:
    context: api
  frontend:
    context: frontend

deploy:
  - helm upgrade --install movies chart
    --set api.image=${OKTETO_BUILD_API_IMAGE}
    --set frontend.image=${OKTETO_BUILD_FRONTEND_IMAGE}

dev:
  api:
    command: yarn start
    sync:
      - api:/src
    forward:
      - 9229:9229
    services:
    - selector:
         app.kubernetes.io/component: frontend
      sync:
      - frontend:/usr/src/app
  frontend:
    image: okteto/node:14
    command: bash
    sync:
      - frontend:/usr/src/app
```
3. Run `okteto up`
4. Wait until it's in development
5. Run  `kubectl get deployments frontend-okteto -o yaml` and check that the label `detached.dev.okteto.com` is empty

**Expected behavior**
The label should be the name of the service

**Desktop (please complete the following information):**
- Version 2.14.0

**Comment by andreafalzetti** [comment]
@jLopezbarb I was able to reproduce it, however it would be helpful to have an example where the label detached is successfully added. Could you help me with that?

I've tried a few examples and variations of the okteto manifest but my deploymenys never have that label 🤔

**Comment by jLopezbarb** [comment]
Sorry, I thought I answered your question but it seems I forgot to press comment button 😅. 

The label dettached value should be the name of the deployment/statefulset. 
Probably this test adds the label correctly:
```
icon: https://apps.okteto.com/movies/icon.png

build:
  api:
    context: api
  frontend:
    context: frontend

deploy:
  - helm upgrade --install movies chart
    --set api.image=${OKTETO_BUILD_API_IMAGE}
    --set frontend.image=${OKTETO_BUILD_FRONTEND_IMAGE}

dev:
  api:
    command: yarn start
    sync:
      - api:/src
    forward:
      - 9229:9229
    services:
    - name: frontend
      sync:
      - frontend:/usr/src/app
  frontend:
    image: okteto/node:14
    command: bash
    sync:
      - frontend:/usr/src/app
```

**Comment by andreafalzetti** [comment]
@jLopezbarb thanks for sharing the new manifest!

I've tried but getting

```
 !  Build 'api': Dockerfile 'Dockerfile' is not in a relative path to context 'api'
 x  Error building service 'api': invalid build context: 'api' does not exist
```

Any idea?

**Comment by andreafalzetti** [comment]
I was getting this issue, @jLopezbarb had a chat to resolve it, the following is the working manifest to reproduce the correct behavioir:

<img width="939" alt="Screenshot 2023-04-10 at 10 39 30" src="https://user-images.githubusercontent.com/2318450/230935978-cda3186a-eb37-4e73-8473-4581ff52f592.png">


```yaml
icon: https://apps.okteto.com/movies/icon.png

build:
  api:
    context: api
  frontend:
    context: frontend

deploy:
  - helm upgrade --install movies chart
    --set api.image=${OKTETO_BUILD_API_IMAGE}
    --set frontend.image=${OKTETO_BUILD_FRONTEND_IMAGE}

dev:
  api:
    command: yarn start
    sync:
      - api:/src
      - frontend:/frontend
    forward:
      - 9229:9229
    persistentVolume:
      enabled: true
      storageClass: standard
      size: 1Gi
    services:
    - name: frontend
      sync:
      - frontend:/usr/src/app
  frontend:
    image: okteto/node:14
    command: bash
    sync:
      - frontend:/usr/src/app
```

After doing `okteto up` and choosing the `api` I was able to see the detatched label set correctly

```
$ kubectl get deployments frontend-okteto -n andrea -o yaml | grep detached
detached.dev.okteto.com: frontend
```
