### ISSUE TITLE
okteto up replicas should be 1 in services

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3485]
**Describe the bug**
We are not changing the number of replicas specified in the services section under the dev section ([we do for the main service](https://github.com/okteto/okteto/blob/master/pkg/k8s/apps/translate.go#L81)). We should always have one replica minimum in the services that are in detached dev mode.

**To Reproduce**

1. Deploy https://github.com/okteto/movies-with-helm
2. Run the following command: `kubectl scale deployment frontend --replicas=0` 
3. Modify the `okteto.yml` to be:
```yaml
icon: https://apps.okteto.com/movies/icon.png

build:
  api:
    context: api
  frontend:
    context: frontend

deploy:
  - helm upgrade --install movies chart
    --set api.image=${OKTETO_BUILD_API_IMAGE}
    --set frontend.image=${OKTETO_BUILD_FRONTEND_IMAGE}

dev:
  api:
    command: yarn start
    sync:
      - api:/src
    forward:
      - 9229:9229
    services:
    - selector:
         app.kubernetes.io/component: frontend
      sync:
      - frontend:/usr/src/app
  frontend:
    image: okteto/node:14
    command: bash
    sync:
      - frontend:/usr/src/app
```
3. Run `okteto up`
4. Wait until it's in development
5. Run  `kubectl get deployments` and check that the frontend replicas is 0

**Expected behavior**
It should have at least 1 replica. If the number of replicas is bigger than 1 we should keep that number for the services

**Desktop (please complete the following information):**

- Version 2.14.0
