### ISSUE TITLE
Can't build a Linux docker on a local M1 mac envirnoment

### ISSUE THREAD

**Issue by AsiaCao** [okteto/okteto#3488]
**Describe the bug**

I have a Kubernetes cluster which runs on Linux x86 OS/platform/container.
My local development environment is a Mac M1 laptop. I have a git repository of a helloworld Python web app with a helm chart (a simple k8s deployment) and a dockerfile.
I want to do development within the Kubernetes cluster via Okteto CLI.
I can use Okteto CLI to build a docker image on my laptop and push it to the docker hub register.
However, the image built by the Okteto CLI is of Darwin Arm platform, but I am expecting Linux x86 or Linux amd64.
I tried using the Okteto CLI “—platform” but it doesn’t work, the pushed image is still the same.
Example command: 
"okteto build --platform "linux/amd64" -l info”

I also tried adding a "platform" section in my Okteto build file, but it still doesn't change anything.

**Desktop (please complete the following information):**

- OS: macOS M1
- Okteto cli version of 2.13.0 (installed it from brew. 

**Additional context**

I also read https://github.com/okteto/okteto/issues/2921, but i'm not sure what's the correct fix, would appreciate someone shed the light here.

**Dockerfile**

```
ARG PY_VER=3.10
FROM ubuntu:22.04

RUN apt-get update && apt-get install -yq curl wget jq vim tldr silversearcher-ag tree xclip bat magic-wormhole net-tools

RUN echo `python -V`
```

**Okteto build file**

```
name: vision_app

# The build section defines how to build the images of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#build
build:
  training:
    context: .
    dockerfile: Dockerfile
    image: asiacao/vision-app
    platform: linux/amd64

deploy:
  - 'helm upgrade --install training chart'

dev:
  training:
    image: ${OKTETO_BUILD_TRAINING_IMAGE}
    command: bash
    workdir: /usr/src/app
    sync:
      - .:/usr/src/app
    environment:
      - name=$USER
```
