### ISSUE TITLE
okteto up hangs when an initContainer crashes

### ISSUE THREAD

**Issue by Mark90** [okteto/okteto#3503]
**Describe the bug**

We have an okteto manifest which deploys a helm chart, which installs a k8s Deployment with `initContainers:`  being executed prior to the actual `containers:`.
When one of the initContainers fail, `okteto up` hangs on "Pulling image .." indefinitely.
The okteto dashboard does show there's an error in the init container, but without logs.

**To Reproduce**

1. Okteto manifest with in the `deploy` section a helm install for a k8s Deployment with [initContainers:](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) - one of these init containers should exit with an error to reproduce
2. Run `okteto up` - it hangs indefinitely on "Pulling image"

**Expected behavior**

I think ideally the up command would detect that the k8s Deployment isn't healthy, perhaps through checking liveness/readiness probe.

**Cluster/okteto version**

K8s: v1.24.9
Chart Version: 1.6.0
App Version 0e048659

**Comment by jLopezbarb** [comment]
Hi @Mark90, I was able to reproduce it. Right now we don't have an ETA on when it will be fixed, but I have added the labels to check if anyone from the community can work on this. The scenario to reproduce it is:
`k8s.yml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-init-container
  template:
    metadata:
      labels:
        app: failing-init-container
    spec:
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'exit 1'] # This will cause the init container to fail
      containers:
      - name: main-container
        image: nginx
        ports:
        - containerPort: 80
```
and the following `okteto.yml`
```yaml
name: k8s

deploy:
  - kubectl apply -f k8s.yml

dev:
  failing-init-container:
    image: okteto/dev:latest
    command: bash
    sync:
      - .:/usr/src/app
```
