### ISSUE TITLE
Okteto silently discards most Device Manager resource claims

### ISSUE THREAD

**Issue by The-Loeki** [okteto/okteto#3563]
**Describe the bug**

Any device management statement in the `resource: limits` section that is not either `nvidia.com/gpu` or `amd.com/gpu` is silently discarded.

**To Reproduce**

We use for example the FUSE plugin:

```yaml

context: $OKTETO_CONTEXT
dev:
  container-sdk:
    autocreate: true
    initContainer:
      image: okteto/bin:1.4.2
    image: quay.io/buildah:latest
    command:
    - bash
    - -l
    persistentVolume:
      enabled: false
    sync:
    - .:/src
    resources:
      limits:
        github.com/fuse: 1
    volumes:
    - /var/lib/containers
    workdir: /src
```

**Expected behavior**

Device Management and it's general syntax is GA since 1.26; `<device namespace>/<resource>: <value>` is the more generic syntax.
See also for example also the [Generic Device Plugin](https://github.com/squat/generic-device-plugin) (`squat.ai/video: 1`) or [Intel's drivers](https://github.com/intel/intel-device-plugins-for-kubernetes) (`sgx.intel.com: epc`)

**Desktop (please complete the following information):**

- OS: RHEL
- Version 7/8, Okteto 2.14.2

**Additional context**
`okteto` seems hardcoded to only evaluate and pass on `nvidia.com/gpu`  and `amd.com/gpu`:
https://github.com/okteto/okteto/blob/71bd808464b80980bf5fc361cb1bc8156835f7c8/pkg/k8s/apps/translate.go#L263
https://github.com/okteto/okteto/blob/71bd808464b80980bf5fc361cb1bc8156835f7c8/pkg/model/const.go#L159
