### ISSUE TITLE
Use resources block from docker-compose.yaml file

### ISSUE THREAD

**Issue by alvaro-quiqup** [okteto/okteto#3621]
**Is your feature request related to a problem? Please describe.**
I'm frustrated trying to request gpu resources when using docker-compose file. Doesn't seem to be possible.

**Describe the solution you'd like**
After running `okteto up` I would like to see my pods requested gpus and they running on nodes with gpus available.

**Describe alternatives you've considered**
Writing the okteto.yaml file from scratch, but is a pain because I already have a working docker-compose file, I just want okteto to use the `resources` block from it.

**Comment by alvaro-quiqup** [comment]
Hi @jLopezbarb , I'm using this okteto file:

```
deploy:
   compose: docker-compose.yml
dev:
   rasa-chat-server:
      autocreate: true
      resources:
         limits:
            gpu: 1
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
```

And this doesn't request gpus, is spawning the pod on a normal node.
