### ISSUE TITLE
Creating a user with a utf8 symbol in name

### ISSUE THREAD

**Issue by pboers1988** [okteto/okteto#3647]
**Describe the bug**
When a user is enrolled into okteto through an identity provider and they have a utf8 symbol in their name, for example è or ç they experience a 503 service temporarily unavailable response from okteto. This likely has to do with the fact that the username gets mapped towards a k8s namespace name which does not accept these characters. The validation regex for the name of a k8s namespace is: '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')'

**To Reproduce**

1. Create a mapping with an identity provider and map the name key to externalIDKey

```
auth:
  openid:
      mapping:
        ....
        externalIDKey: name
        nameKey: preferred_name
        emailKey: email
        ......
```
2. Create a user with a  utf8 symbol in their name.

**Expected behavior**
Allow the user to login.

**Desktop (please complete the following information):**

Chart Version
1.6.0

App Version
0e048659

CLI Version
2.13.0
