### ISSUE TITLE
Build Args refering to another build are not expanded

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3684]
**Describe the bug**
If I use an okteto build environment as a build arg the build arg is not getting the correct value. I expect that this build arg uses the okteto env var that I provided

**To Reproduce**

1. Create the following Dockerfile:
```Dockerfile
FROM alpine

ARG KEY
RUN echo testing: $KEY
```
1. Create the following okteto manifest:
```yaml
build:
  test:
    context: .
    args:
      KEY: hello
  test-2:
    context: .
    args:
      KEY: $OKTETO_BUILD_TEST_IMAGE
    depends_on:
      - test
```
1. Run `okteto build --progress plain -f okteto.yml --no-cache`
1. See that the `$OKTETO_BUILD_TEST_IMAGE` is not propagated

**Expected behavior**
I want that the build arg gets into the image
