### ISSUE TITLE
How is okteto build [service ...] --build-arg supposed to work?!

### ISSUE THREAD

**Issue by proof-nicholas** [okteto/okteto#3746]
**Describe the bug**
I'm trying to pass in a build argument that will set a build argument when building a docker image via the okteto command line.  Ideally, I would like it to override whatever is defined in the okteto manifest.  I've tried various combinations of passing --build-arg to okteto build to no avail.  How is it supposed to be used?

**To Reproduce**

1. Here is an example okteto manifest: 
```
...
build:
  web:
    context: .
    dockerfile: Dockerfile.web
    args:
      MY_BUILD_ARG: test123
```
1. Try and build the web image and override the value of MY_BUILD_ARG: `okteto build web --build-arg "MY_BUILD_ARG=plzwork"`
1. The docker image is still built with the value of test123
1. If I remove the `args` section from okteto manifest, the docker build fails because the arg is not specified!

**Expected behavior**
Specifying `--build-arg` with the `okteto build` command should override whatever value is specified statically in the manifest.  Currently it doesn't do that, and frankly I'm not sure how it is supposed to be used because even without an `args` section defined, it still isn't passed to the docker build.

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.16.3

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by pchico83** [comment]
@proof-nicholas could you share your `Dockerfile`?

**Comment by proof-nicholas** [comment]
The relevant part is the following:
```
ARG MY_BUILD_ARG=oldversion
FROM okteto.dev/staging-webdev:$MY_BUILD_ARG AS build
...
...
```

**Comment by pchico83** [comment]
> The relevant part is the following:
> 
> ```
> ARG MY_BUILD_ARG=oldversion
> FROM okteto.dev/staging-webdev:$MY_BUILD_ARG AS build
> ...
> ...
> ```

@proof-nicholas you need to refer the image using `OKTETO_BUILD_XXX` envvars.
For example, an okteto manifest like this:
```
build:
  base:
    dockerfile: Dockerfile.base

  api:
    dockerfile: Dockerfile
    depends_on: base
    args:
       - BASE_IMAGE: ${OKTETO_BUILD_BASE_IMAGE}
``` 
and a Dockerfile like this:
``` 
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
```
