### ISSUE TITLE
`timeout` doesn't return any error after specified time elapsed

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3849]
The properties `dev.<svc>.timeout` and `dependencies.<svc>.timeout` don't seem to have any effect. To reproduce:

1. Clone https://github.com/okteto/movies-frontend
2. Change the manifest as follows:
```yaml
build:
  frontend:
    context: .
    dockerfile: Dockerfile
  frontend-dev:
    context: .
    dockerfile: Dockerfile
    target: dev
dependencies:
  multi-repo:
    repository: https://github.com/okteto/movies-multi-repo
    timeout: 1s
deploy:
  - name: Deploy Frontend
    command: helm upgrade --install movies-frontend chart --set image=${OKTETO_BUILD_FRONTEND_IMAGE}
dev:
  frontend:
    image: ${OKTETO_BUILD_FRONTEND_DEV_IMAGE}
    command: yarn start
    timeout: 1s
    sync:
      - .:/src
```
3. Run `okteto deploy --wait` 
4. The deployment will suceed despite a timeout of 1 second.
