### ISSUE TITLE
okteto up uses old image even if I change Dockerfile

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3871]
Running `okteto up` in the following scenario should just work without any errors returned from the `checker.sh` script. However, there is a weird behaviour happening because if I rename/delete in Dockerfile the variable `ENV_IN_IMAGE` and I run `okteto up` again, it will continue to work.

I narrowed down this issue to the env getter in the up command, when we create the list of env vars to use for the dev container, some of them comes from the docker image. In this case `busybox`. The problem is that once the digest is created against `busybox`, the digest stays the same even if I change the env var in the Dockerfile, because the file/content is not taking into account when calculating if we should re-build the image. See related code: https://github.com/okteto/okteto/blob/master/cmd/up/activate.go#L99-L110

I think the code mentioned in `activate.go` should also hash the file at least, or ideally checking if the env vars have changed since.

```yaml
# okteto.yml

deploy:
  compose: docker-compose.yml
dev:
  svc:
    context: svc
    namespace: user
    mode: hybrid
    command: bash ./checker.sh
    reverse:
    - 8080:8080
    envFiles:
    - .env
    environment:
    - TEST_ENV_VAR1=test-value1
    metadata:
      annotations:
        e2e/test-1: annotation-1
      labels:
        custom.label/e2e: "true"
    annotations:
      deprecated.annotation.format: deprecated-annotation-1
```

```yaml
# docker-compose.yml

services:
 svc:
  build: .
  environment:
  - ENV_IN_POD=value_from_pod
```

```Dockerfile
# Dockerfile
FROM busybox
ENV ENV_IN_IMAGE value_from_image
env 
```

```bash
# checker.sh
#!/bin/bash

set -e

check_env_var() {
  local name="$1"
  local value="$2"
  local var_value="${!name}"

  if [ "$var_value" != "$value" ]; then
    echo "$name should be '$value', got '$var_value' instead"
    exit 1
  fi
}

declare -A env_vars=(
  ["TEST_ENV_VAR1"]="test-value1"
  ["TEST_ENV_FILE_VAR1"]="from-file-1"
  ["ENV_IN_POD"]="value_from_pod"
  ["ENV_IN_IMAGE"]="value_from_image"
)

if [ "$#" -ne 0 ]; then
  echo "This script does not accept any argument, got $# instead"
  exit 1
fi

for name in "${!env_vars[@]}"; do
  check_env_var "$name" "${env_vars[$name]}"
done

echo "!Successful envs check!"
exit 0
```
