### ISSUE TITLE
I can't deploy a compose with a generated image from the build

### ISSUE THREAD

**Issue by jvc5546** [okteto/okteto#3878]
**Describe the bug**
I can't deploy my application because whenever I try to deploy my compose I get the following error:
` x  Invalid service 'service': image cannot be empty`. This bug is a regression because i can make it work downgrading my CLI to 2.16.5 by running: `curl https://get.okteto.com -sSfL | OKTETO_CHANNEL=stable OKTETO_VERSION=2.16.5 sh`

**To Reproduce**
1. Create the following okteto manifest:
```yaml
build:
  service:
    context: .
    dockerfile: ./Dockerfile
deploy:
  compose:
    - file: ./docker-compose.yml
```
2. Create the following docker compose:
```yaml
services:
  service:
    image: ${OKTETO_BUILD_SERVICE_IMAGE}
    command: sleep 100
```
3. Create the following Dockerfile:
```Dockerfile
FROM alpine

RUN echo hello
```
4. Download CLI 2.18.0:
```bash
curl https://get.okteto.com -sSfL | OKTETO_CHANNEL=stable OKTETO_VERSION=2.18.0 sh
```
5. Run `okteto deploy` and check that it fails:
```
 i  Using jlopezbarb @ cloud.okteto.com as context
 x  Invalid service 'service': image cannot be empty
```
6. Download CLI 2.16.5:
```bash
curl https://get.okteto.com -sSfL | OKTETO_CHANNEL=stable OKTETO_VERSION=2.16.5 sh
```
7. Run `okteto deploy` and check that it's working:
```
 ✓  Image 'registry.cloud.okteto.net/jlopezbarb/test-service:okteto' successfully pushed
 ✓  Service 'service' created
 ✓  Compose 'test' successfully deployed
 ✓  Development environment 'test' successfully deployed
 i  Run 'okteto up' to activate your development container
```

**Expected behavior**
It should work on the latest version
