### ISSUE TITLE
Support `platform` key on the okteto manifest

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3915]
**Is your feature request related to a problem? Please describe.**
I’m working on a Mac with an M1 processor.  I have this manifest:
```
build:
  menu:
    context: menu
    image: ramiro/tacoshop-menu:latest
  kitchen:
    context: kitchen
    image: ramiro/tacoshop-kitchen:latest
  check:
    context: check
    image: ramiro/tacoshop-check:latest
deploy:
- name: deploy cloudinfra
  command: |
     helm upgrade --install localstack localstack-charts/localstack
- name: deploy services
  command: |
    helm upgrade --install menu ./menu/chart
    helm upgrade --install kitchen ./kitchen/chart
    helm upgrade --install check ./check/chart
```

I ran okteto build and then okteto deploy to deploy my dev env on a k8s cluster (without okteto installed in my cluster).

```
Every pod I deploy is failing like this:
❯ kubectl get pods
NAME                          READY   STATUS                       RESTARTS   AGE
menu-d98c9cf87-t8g9k          0/1     CreateContainerConfigError   0          22m
kitchen-86cd85778c-xwdpn      0/1     CreateContainerConfigError   0          21m
check-5cb6b997bc-j42sm        0/1     CreateContainerConfigError   0          21m
```

I’m assuming this is because ` okteto build` is  building an ARM image instead of an AMD64.

**Describe the solution you'd like**
I want to tell Okteto to build this using the AMD64 platform. 

**Describe alternatives you've considered**
I can build each image with docker or okteto build --platform. But this would make me lose the 'one command and it's done'  experience.  

Another alternative is to have an env var similar to `DOCKER_DEFAULT_PLATFORM`.
