### ISSUE TITLE
fix labels list for `okteto preview list` default view

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#3927]
**Describe bug**

When running `okteto preview list` and the preview had labels, no labels where shown at the default view

```
❯ okteto preview list
 i  Using - @ - as context
Name                   Scope     Sleeping  Labels
upbeat-feynman-teresa  personal  false     -
```

```
❯ ok preview list -o json
[
 {
  "name": "upbeat-feynman-teresa",
  "scope": "personal",
  "sleeping": false,
  "labels": [
   "other",
   "testing"
  ]
 }
]
```

```
❯ ok preview list -o yaml
- name: upbeat-feynman-teresa
  scope: personal
  sleeping: false
  labels:
  - testing
  - other
```

This was not happening when using `yaml` or `json` output

This bug was [introduced](https://github.com/okteto/okteto/pull/3804/files#diff-1de660ef246a78c71aa7be984185a6ab279c12c708e9d6e27799b2a4e0278ddaL79) when adding the output flag to the command, this PR reverts the logic that added the preview labels to the default view.
