### ISSUE TITLE
OKTETO_DOMAIN doesn't resolve when used as part of an env var in a docker-compose file

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3932]
**Describe the bug**
I have this docker compose file:
```
services:
  vote:
    build: .
    ports:
      - 8080:8080
    environment:
      - PUBLIC_URL=https://vote-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}/oauth2/callback

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data
volumes:
  redis:
```

When I see the deployment created by Okteto, the value of `PUBLIC_URL` is "https://vote-ramiro./oauth2/callback". Okteto is not filling up `OKTETO_DOMAIN` 

**Desktop (please complete the following information):**

- OS: macos
- Version 2.19
- Okteto Self-Hosted 1.11.1
