### ISSUE TITLE
[Hybrid development] Env vars stored in k8s configmaps are not propagated

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3936]
**Describe the bug**
If I define an environment variable in a k8s configmap and then try to use a service that uses that value, using hybrid the env var is not propagated and its value is empty.

**To Reproduce**
Steps to reproduce the behavior using movies with helm:

1. Run `git clone https://github.com/okteto/movies-with-helm`
1. Add this file `chart/templates/cm.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  CM_ENV_VAR: "hello-from-cm"
```
1. Add the following to `spec.template.spec.initContainers[load-data].env` and `spec.template.spec.containers[api].env`
```yaml
            - name: OKTETO_TEST_CM_ENV_VAR
              valueFrom:
                configMapKeyRef:
                  name: test-cm
                  key: CM_ENV_VAR
```
1. Run `okteto deploy --build`
1. Run `okteto up api`
1. When the interactive shell is open write `printenv | grep OKTETO_TEST_CM_ENV_VAR`
1. Check that the value is: `OKTETO_TEST_CM_ENV_VAR=`

**Expected behavior**
The env var set from the configmap should be populate with its value.

**Additional context**
Fix similar to: https://github.com/okteto/okteto/pull/3931
