### ISSUE TITLE
Can't use existing volume with new container

### ISSUE THREAD

**Issue by shepherd1530** [okteto/okteto#4017]
**Describe the bug**
I have a postgres volume that stores my data. I want to attach a postgres instance to it but my deployment is failing.

**To Reproduce**
```okteto deploy```

I am getting the below error.

```
❯ okteto deploy
 i  Using xxxx @ xxxx.okteto.dev as context
 i  Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'
 ✓  Kubernetes service 'postgres' updated
 x  Error updating volume 'postgres-data': Volume size can not be less than previous value
```

My docker compose file looks like the below.

```
version: '3.3'
services:
  postgres:
    restart: always
    image: postgres:15
    ports:
      - '5432:5432'
    expose:
      - 5432
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  
```
