### ISSUE TITLE
how to configure okteto.yaml with config-map volumes

### ISSUE THREAD

**Issue by yang1992** [okteto/okteto#4395]
GPT tell okteto.yaml:

```
name: test-dev
autocreate: true
image: dev:0.0.8
initContainer:
  image: okteto:1.4.0
persistentVolume:
  enabled: false
config:
  - name: test-config
    mountPath: /user/local/test/conf/
    subPath: config.toml
sync:
  - .:/user/local/test
command: ["bash"]  
```

when use command: oketeto up
error: config not found in type model.devType
