### ISSUE TITLE
`okteto up` can delete almost every file in the directory.

### ISSUE THREAD

**Issue by joneshf-cn** [okteto/okteto#522]
**Describe the bug**

`okteto up` can delete almost every file in the directory.

**To Reproduce**
1. Run `okteto up`.

    ```console
    $ okteto up
    ✓  Development environment activated
    x  The synchronization service hasn't made any progress in the last 30 seconds
       Help us improve okteto by filing an issue in https://github.com/okteto/okteto/issues/new.
       Please include your syncthing log (/Users/hjones/.okteto/default-orders-syncthing.log) if possible.
    ```

1. Almost the entire directory contents are gone:

    ```console
    $ tree -a        
    .
    ├── .stignore
    ├── okteto.yml
    └── output
        └── Test.Log
            ├── externs.json
            └── index.js

    2 directories, 4 files
    ```

    I don't have a before tree because I have to setup the directory again, but suffice to say, there were many more than four files in this directory.

**Expected behavior**

The files should not be deleted.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: High Sierra 10.13.6 (17G2208)

**Additional context**

okteto.yml
```YAML
name: orders
image: node:10.15.3-stretch
command:
  - npx
  - nodemon
  - --watch dev.js
  - dev.js
forward:
  - 8080:8080
mountpath: /home/node
workdir: /home/node/.build/dist
```
