### ISSUE TITLE
GPUs specified in the resources section of an okteto.yml are ignored

### ISSUE THREAD

**Issue by kklemon** [okteto/okteto#548]
**Describe the bug**
When specifying GPUs in the `resources` section of a `okteto.yml`, this gets ignored in the deployment.

**To Reproduce**
Example manifest:
```yaml
name: demo
image: tensorflow/tensorflow:latest-gpu
command: ["bash"]
resources:
  limits:
    nvidia.com/gpu: 1
```
**Expected behavior**
The resource specification should be translated properly into the corresponding k8s deployment.
