### ISSUE TITLE
redeploy after "okteto build" doesn't work

### ISSUE THREAD

**Issue by jagedn** [okteto/okteto#607]
**redeploy after `okteto build` doesn't work**

I have deployed a java application and want to redeploy a new version publishing a new image with `okteto build -t jagedn/grails4k8s .` but the redeploy still use the old image

If I deploy via `docker build` and `docker push` the redeploy use the last image

In both case I checked my hub.docker.com repository and it appears up-to-date

**To Reproduce**

- okteto build -t jagedn/grails4k8s .
- touch k8s.yml
- kubectl apply -f k8s.yml

the container is destroyed and a new container is created but with the same version

**Expected behavior**

Deploy the last version uploaded to the registry

**Desktop (please complete the following information):**
 - OS: linux mint
 - Version okteto 1.6.3

Dockerfile:
```
FROM adoptopenjdk/openjdk11-openj9:jdk-11.0.1.13-alpine-slim
MAINTAINER John Doe "john.doe@example.com"

WORKDIR /app
COPY build/libs/*.jar application.jar

CMD ["sh", "-c","java -Djava.security.egd=file:/dev/./urandom -jar /app/application.jar --server.port=$PORT"]
```

k8s.yml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app # a name for the deployment
  labels:
    app: app # tag with the app, labels are kind of like tags
spec:
  replicas: 2 # tells deployment to run 1 pods matching the template
  selector:
    matchLabels:
      app: app # points to label key in pod template below
  template: # pod template
    metadata:
      name: app
      labels:
        app: app # the pod key label, labels are like tags
        deployed: 2019-12-26_02
    spec: # containers in the pod
      containers:
      - image: jagedn/grails4k8s
        name: app #just normal docker name
        imagePullPolicy: "Always"
        env:
          - name: PORT
            value: "8080"
        ports:
          - containerPort: 8080
            name: server
        resources:
          limits:
            memory: "1G"
            cpu: "1000m"
          requests:
            memory: "1G"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: app # a name for the service
  labels:
    app: app # tag the app label onto the service as well
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app # points to the label key for deployment
```
