### ISSUE TITLE
Reverse does not work on non-root images

### ISSUE THREAD

**Issue by shyim** [okteto/okteto#688]
**Describe the bug**

**To Reproduce**
```yaml
name: shopware
namespace: sw5
image: shyim/shopware-cli:php74
command: ["bash"]
mountpath: "/var/www/html"
forward:
    - 8080:8080
reverse:
    - 9000:9000
```
2. Run that okteto.yaml
3. Wait some time and it cancels after 1-2 minutes with error

**Expected behavior**
Its working

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version current

**Additional context**
