### ISSUE TITLE
"okteto up" should ignore the some securityGroup fields

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#696]
**Describe the bug**
My deployment is using:
```
     securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
```
and my dev image is root. `okteto up` fails with permission errors.

**Expected behavior**
It should work. "okteto up" should unset:
```
     securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
```
