### ISSUE TITLE
Feature discussion - okteto detached mode

### ISSUE THREAD

**Issue by cameronbraid** [okteto/okteto#817]
In my development cluster I would like to be able to run okteto in a `detached mode` meaning that after I run `okteto up --detached` (for example), then if I exit the shell the okteto environment remains up.

When using the detached mode I don't need syncthing running.   Instead my solution for accessing my workspace is to mount a persistent volume in the cluster and mount it at /app (once  https://github.com/okteto/okteto/issues/811#issuecomment-613308288 is implemented)

This way I can have a 'semi permanent' development environment running my development cluster. 
 I can then connect to it via vscode remote ssh, or via a ssh terminal, whenever I wish to do development.

**Comment by rberrelleza** [comment]
If you exit `okteto up` and don't run `okteto down`, your development environment will be up and running. 

The big issue we have is that while `up` is running, there's a port-forward running, which permits SSH'ing into the pod. How would you access the pod in detached mode?  

Would having the  the `up` process was running in the background, without a terminal, enable your use case?

**Comment by agustinsilvano** [comment]
Hey guys! 
Now I'm using local k8s for development and I've installed okteto to debug the running pods. My scenario is the following: I have an API in PHP and a web app in PHP too, and I want to make okteto up in both projects at the same time using only one terminal.  

This is not anything that blocks the usual workflow but could be an awesome upgrade!

Thanks!

PD: I'm thinking about something like docker whit his detached mode.

**Comment by pchico83** [comment]
@agustinsilvano is you API and Web App on the same git repo? or do they have a different code base?
Also, could you share your okteto manifests? Just trying to understand how to better support your use case

**Comment by agustinsilvano** [comment]
@pchico83 I've two projects, one for API and another for the web app.

The okteto.yaml file looks like:
``` yaml
name: pfi-webapp-dev
image: agustinsilvanoatt/pfi-api-server-debug:v4
command:
  - cd /var/www/html && service apache2 start
workdir: /okteto
forward:
  - 31081:8080
  - 31082:80
reverse:
  - 9000:9000
volumes:
  - /root/.composer/cache
persistentVolume:
  enabled: true
```

Both are similar.
