### ISSUE TITLE
Share global volumes with "services"

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#830]
**Is your feature request related to a problem? Please describe.**
I want to share a cache folder with `services`

**Describe the solution you'd like**
Ability to share global volumes using this syntax:
```
name: api
volumes:
  - /home/rails/bundle
services:
  - name: worker
    volumes:
       - /home/rails/bundle
```

**Describe alternatives you've considered**
Move cache folders under the working folder.
This is inconvenient because it creates differences between development and production.
