### ISSUE TITLE
Support for env vars with default values in the image

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#874]
**Describe the bug**
I have this definition in my stack

```
db:
    image: postgres:${POSTGRES_VERSION:-9.6.15-alpine}
    environment:
      - POSTGRES_USER=devto
      - POSTGRES_PASSWORD=devto
      - POSTGRES_DB=PracticalDeveloper_development
    ports:
      - 5432
```

When deployed, the image was `postgres:`. It would be nice if to have support for default values in the env vars, like in docker-compose.

**Desktop (please complete the following information):**
 - OS: macos
 - Version: 1.8.8
