### ISSUE TITLE
when yaml has service account info deployment fails 

### ISSUE THREAD

**Issue by maxandersen** [okteto/okteto#879]
**Describe the bug**
When deploying something like this:

```
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-14 - 08:38:51 +0000"
    dev.okteto.com/auto-ingress: "true"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "jugchdemo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "jugchdemo"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-14 - 08:38:51 +0000"
    dev.okteto.com/auto-ingress: "true"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "jugchdemo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "jugchdemo"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "jugchdemo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-14 - 08:38:51 +0000"
    dev.okteto.com/auto-ingress: "true"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "jugchdemo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "jugchdemo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "jugchdemo"
      app.kubernetes.io/version: "1.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: "2020-05-14 - 08:38:51 +0000"
        dev.okteto.com/auto-ingress: "true"
        app.quarkus.io/commit-id: "<<unknown>>"
        app.quarkus.io/vcs-url: "<<unknown>>"
      labels:
        app.kubernetes.io/name: "jugchdemo"
        app.kubernetes.io/version: "1.0-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "docker.io/maxandersen/jugchdemo:1.0-SNAPSHOT"
        imagePullPolicy: "Always"
        name: "jugchdemo"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "jugchdemo"
```

notice the "serviceAccount" that is done as a good practice.

This result in:
```unable to validate against any pod security policy: []"```

I figured out it was the `serviceaccount` by trial and error.

Found two solutions:
remove serviceAccount completely or just use "default" as its name.

**Expected behavior**
Allow deployment to setup serviceaccount.
