### ISSUE TITLE
okteto up times out when running on a newly restarted minikube

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#886]
**Describe the bug**
okteto up fails with a  time out when running on a minikube instance after a restart

**To Reproduce**
1. minkube stop
2. minikube start
3. okteto up
4. Error:
```
couldn't activate your development environment: kubernetes is taking too long to update the 'deployment.kubernetes.io/revision' annotation of the deployment...
```

**Expected behavior**
okteto up should finish

Based on the our investigation, it seems like the timeout   happens while waiting for a service's pod to be redeployed.

**Desktop (please complete the following information):**
 - OS:  Linux
 - Version 1.8.9

**Additional context**
Increasing timeout using #885 seems to solve the issue

**Comment by rberrelleza** [comment]
I was able to reproduce the issue.  Minikube comes with a default storage provisioner, provisioner:k8s.io/minikube-hostpath. This provisioner is configured to store the data under /tmp, which is deleted on a minikube restart. 

This causes any deployment with a volume to fail after a minikube restart with the following error message:

```
      state:
        waiting:
          message: 'stat /tmp/hostpath-provisioner/pvc-2dc00274-4042-4923-b410-7f1d8b640978:
            no such file or directory'
          reason: CreateContainerConfigError
```

I think we need to do a couple of things here:
1. okteto should catch the `CreateContainerConfigError` status error and fail with that, instead of retrying.
1. Document the recommended configuration for minikube+okteto (and kind, and other local cluster options)
1. We could potentially detect if the user is running in minikube and warn if using the hostpath provider + volumes
