### ISSUE TITLE
okteto up doesnt work out of the box for non-privileged users

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#920]
**Describe the bug**
Okteto up fails to complete if the user doesn't have write permissions over the /var/okteto folder.

```
 microservice-starter mkdir: can't create directory '/var/okteto/remote': Permission denied
```

**Comment by lbogdan** [comment]
The okteto config file is pretty much bare:
```
# .okteto.yml
name: foo
namespace: foo
persistentVolume:
  enabled: true
mountpath: /foo
```

**Comment by lbogdan** [comment]
As per the original deployment definition, I guess the only relevant thing is
```yaml
# deployment.yaml
# [...]
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
# [...]
```
